// Every translated string on the about page, one entry per key per language.
// The markup lives in about.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    home: "Home",
    aboutUs: "About Us",
    whoWeAre: "Who We Are",
    aRegisteredKrgEngineeringCompany: "A Registered KRG Engineering Company, Built on Trust",
    brightVolitionWasFoundedIn: "Bright Volition was founded in 2022 as an engineering office specializing in Electrical, Instrumentation, and Mechanical services.",
    downloadOurFullCompanyProfile: "Download Our Full Company Profile",
    ourMission: "Our Mission",
    toEmpowerClientsByProviding: "To empower clients by providing smart, sustainable, and cost-effective engineering services that drive lasting value.",
    companyOverview: "Company Overview",
    foundingVisionMilestonesFutureOutlook: "Founding Vision, Milestones & Future Outlook",
    foundingVision: "Founding Vision",
    leadInInnovativeSustainableAnd: "Lead in innovative, sustainable, and reliable engineering solutions.",
    empowerClientsToAchieveLasting: "Empower clients to achieve lasting excellence.",
    milestones: "Milestones",
    incorporatedLaunchedFirstProductsService: "Incorporated, launched first products & services.",
    broadenedOurServicesAndUpgraded: "Broadened our services and upgraded our office to a registered company in the KRG.",
    diversifiedServicesEnteredNewSectors: "Diversified services; entered new sectors with advanced engineering solutions.",
    futureOutlook: "Future Outlook",
    commitToQualitySustainabilityAnd: "Commit to quality, sustainability, and responsibility.",
    driveInnovationToStayAhead: "Drive innovation to stay ahead of trends.",
    expandGloballyWhileFocusingOn: "Expand globally while focusing on customer satisfaction.",
    ourPolicy: "Our Policy",
    qualityDeliveredByDesign: "Quality, Delivered by Design",
    brightVolitionIsCommittedTo: "Bright Volition is committed to delivering innovative, sustainable, and reliable engineering solutions, product supply, and construction services that meet customer requirements and exceed expectations.",
    thisPolicyProvidesTheFramework: "This policy provides the framework for setting and reviewing our quality objectives and is communicated to all employees and stakeholders to ensure understanding and effective implementation.",
    ensureComplianceWithLegalRegulations: "Ensure compliance with legal regulations and contractual obligations.",
    striveForCustomerSatisfactionThrough: "Strive for customer satisfaction through high-quality products, services, and solutions.",
    fosterACultureOfContinuous: "Foster a culture of continuous improvement in all processes, systems, and performance.",
    empowerEmployeesThroughTrainingTeamwork: "Empower employees through training, teamwork, accountability, and well-being.",
    strengthenPartnershipsWithClientsAnd: "Strengthen partnerships with clients and suppliers to create long-term value.",
    howBvServesItsCustomers: "How BV Serves Its Customers",
    howWeWork: "How We Work",
    confidentialityFirst: "Confidentiality First",
    wePrioritizeTheConfidentialityOf: "We prioritize the confidentiality of both our customers and suppliers, ensuring that all sensitive information remains secure and protected.",
    streamlinedSupplyChain: "Streamlined Supply Chain",
    efficientSupplyChainManagementGuarantees: "Efficient supply chain management guarantees timely delivery, minimizing delays and optimizing performance.",
    uncompromisingQualityReliability: "Uncompromising Quality & Reliability",
    wePartnerWithReputableSuppliers: "We partner with reputable suppliers so every product and service meets the highest standards.",
    tailoredCostEffective: "Tailored & Cost-Effective",
    everySolutionIsScopedAround: "Every solution is scoped around your operational and budget realities.",
    collaborativeApproach: "Collaborative Approach",
    weWorkCloselyWithClients: "We work closely with clients to understand their needs and provide the best possible solutions.",
    commitmentToExcellence: "Commitment to Excellence",
    weAreCommittedToDelivering: "We are committed to delivering excellence in everything we do.",
    whyBvIsTheRight: "Why BV Is the Right Choice",
    customerFocusInnovationResponsibility: "Customer Focus, Innovation & Responsibility",
    customerFocus: "Customer Focus",
    wePlaceAHighValue: "We place a high value on comprehending the specific requirements and obstacles of each client.",
    prioritizingExcellentServiceAndBuilding: "Prioritizing excellent service and building strong, long-term relationships.",
    innovation: "Innovation",
    weStayAheadOfThe: "We stay ahead of the curve with the latest technologies and industry trends.",
    investmentInRDEnables: "Investment in R&D enables cutting-edge solutions that enhance efficiency and productivity.",
    sustainabilitySocialResponsibility: "Sustainability & Social Responsibility",
    offeringEnvironmentallyFriendlyEngineeri: "Offering environmentally friendly engineering solutions.",
    healthSafetyRigorousStandardsFor: "Health & Safety: rigorous standards for workers, clients, and the community.",
    energyEfficientDesignsThatReduce: "Energy-efficient designs that reduce consumption and emissions.",
    csrEngagementSupportingLocalCommunities: "CSR engagement supporting local communities and environmental initiatives.",
    wantToKnowMoreAbout: "Want to Know More About Our Capabilities?",
    seeHowOurEngineeringConstruction: "See how our engineering, construction, and supply capabilities fit your next project.",
    ourServices: "Our Services",
    contactUs: "Contact Us",
  },
  ar: {
    home: "الرئيسية",
    aboutUs: "من نحن",
    whoWeAre: "من نحن",
    aRegisteredKrgEngineeringCompany: "شركة هندسية مسجّلة رسميًا في إقليم كوردستان، مبنية على الثقة",
    brightVolitionWasFoundedIn: "تأسست الإرادة المشرقة عام 2022 كمكتب هندسي متخصص بالخدمات الكهربائية وأجهزة القياس والميكانيكية.",
    downloadOurFullCompanyProfile: "تحميل الملف التعريفي الكامل للشركة",
    ourMission: "مهمتنا",
    toEmpowerClientsByProviding: "تمكين عملائنا من خلال تقديم خدمات هندسية ذكية ومستدامة وفعّالة من حيث التكلفة، تحقق قيمة دائمة.",
    companyOverview: "نظرة عامة عن الشركة",
    foundingVisionMilestonesFutureOutlook: "رؤية التأسيس، المحطات الرئيسية، والتطلعات المستقبلية",
    foundingVision: "رؤية التأسيس",
    leadInInnovativeSustainableAnd: "الريادة في تقديم حلول هندسية مبتكرة ومستدامة وموثوقة.",
    empowerClientsToAchieveLasting: "تمكين العملاء من تحقيق تميّز مستدام.",
    milestones: "المحطات الرئيسية",
    incorporatedLaunchedFirstProductsService: "التأسيس الرسمي وإطلاق أولى المنتجات والخدمات.",
    broadenedOurServicesAndUpgraded: "توسيع الخدمات وترقية المكتب إلى شركة مسجّلة رسميًا في حكومة إقليم كوردستان.",
    diversifiedServicesEnteredNewSectors: "تنويع الخدمات ودخول قطاعات جديدة بحلول هندسية متقدمة.",
    futureOutlook: "التطلعات المستقبلية",
    commitToQualitySustainabilityAnd: "الالتزام بالجودة والاستدامة والمسؤولية.",
    driveInnovationToStayAhead: "دفع الابتكار للبقاء في صدارة التوجهات.",
    expandGloballyWhileFocusingOn: "التوسع عالميًا مع التركيز على رضا العملاء.",
    ourPolicy: "سياستنا",
    qualityDeliveredByDesign: "الجودة، مصممة بعناية",
    brightVolitionIsCommittedTo: "تلتزم الإرادة المشرقة بتقديم حلول هندسية مبتكرة ومستدامة وموثوقة، وتوريد منتجات وخدمات تنفيذ تلبي متطلبات العملاء وتفوق توقعاتهم.",
    thisPolicyProvidesTheFramework: "توفر هذه السياسة الإطار اللازم لوضع ومراجعة أهداف الجودة لدينا، ويتم تعميمها على جميع الموظفين وأصحاب المصلحة لضمان الفهم والتطبيق الفعّال.",
    ensureComplianceWithLegalRegulations: "ضمان الامتثال للأنظمة القانونية والالتزامات التعاقدية.",
    striveForCustomerSatisfactionThrough: "السعي لتحقيق رضا العملاء من خلال منتجات وخدمات وحلول عالية الجودة.",
    fosterACultureOfContinuous: "ترسيخ ثقافة التحسين المستمر في جميع العمليات والأنظمة والأداء.",
    empowerEmployeesThroughTrainingTeamwork: "تمكين الموظفين من خلال التدريب والعمل الجماعي والمسؤولية والاهتمام بسلامتهم.",
    strengthenPartnershipsWithClientsAnd: "تعزيز الشراكات مع العملاء والموردين لخلق قيمة طويلة الأمد.",
    howBvServesItsCustomers: "كيف تخدم الإرادة المشرقة عملاءها",
    howWeWork: "كيف نعمل",
    confidentialityFirst: "السرّية أولًا",
    wePrioritizeTheConfidentialityOf: "نُولي أولوية لسرّية عملائنا ومورّدينا، لضمان بقاء كل المعلومات الحساسة آمنة ومحمية.",
    streamlinedSupplyChain: "سلسلة توريد فعّالة",
    efficientSupplyChainManagementGuarantees: "إدارة فعّالة لسلسلة التوريد تضمن التسليم في الوقت المحدد وتقلل التأخير وتُحسّن الأداء.",
    uncompromisingQualityReliability: "جودة وموثوقية لا تقبل التنازل",
    wePartnerWithReputableSuppliers: "نتعامل مع مورّدين موثوقين لضمان أن يلبي كل منتج وخدمة أعلى المعايير.",
    tailoredCostEffective: "حلول مخصصة وفعّالة من حيث التكلفة",
    everySolutionIsScopedAround: "كل حل مصمم وفق احتياجاتك التشغيلية وميزانيتك.",
    collaborativeApproach: "نهج تعاوني",
    weWorkCloselyWithClients: "نعمل عن قرب مع العملاء لفهم احتياجاتهم وتقديم أفضل الحلول الممكنة.",
    commitmentToExcellence: "الالتزام بالتميّز",
    weAreCommittedToDelivering: "نحن ملتزمون بتقديم التميّز في كل ما نقوم به.",
    whyBvIsTheRight: "لماذا الإرادة المشرقة هي الخيار الصحيح",
    customerFocusInnovationResponsibility: "التركيز على العميل، الابتكار، والمسؤولية",
    customerFocus: "التركيز على العميل",
    wePlaceAHighValue: "نُولي أهمية كبيرة لفهم المتطلبات والتحديات الخاصة بكل عميل.",
    prioritizingExcellentServiceAndBuilding: "إعطاء الأولوية لخدمة متميزة وبناء علاقات قوية وطويلة الأمد.",
    innovation: "الابتكار",
    weStayAheadOfThe: "نواكب أحدث التقنيات وتوجهات الصناعة باستمرار.",
    investmentInRDEnables: "استثمارنا في البحث والتطوير يتيح حلولًا متطورة تُعزز الكفاءة والإنتاجية.",
    sustainabilitySocialResponsibility: "الاستدامة والمسؤولية المجتمعية",
    offeringEnvironmentallyFriendlyEngineeri: "تقديم حلول هندسية صديقة للبيئة.",
    healthSafetyRigorousStandardsFor: "الصحة والسلامة: معايير صارمة للعمال والعملاء والمجتمع.",
    energyEfficientDesignsThatReduce: "تصاميم موفرة للطاقة تقلل الاستهلاك والانبعاثات.",
    csrEngagementSupportingLocalCommunities: "مبادرات مسؤولية مجتمعية تدعم المجتمعات المحلية والبيئة.",
    wantToKnowMoreAbout: "تريد معرفة المزيد عن إمكانياتنا؟",
    seeHowOurEngineeringConstruction: "اكتشف كيف تناسب قدراتنا الهندسية والتنفيذية والتوريدية مشروعك القادم.",
    ourServices: "خدماتنا",
    contactUs: "تواصل معنا",
  },
  ku: {
    home: "سەرەکی",
    aboutUs: "دەربارەمان",
    whoWeAre: "دەربارەمان",
    aRegisteredKrgEngineeringCompany: "کۆمپانیایەکی ئەندازیاری بە فەرمی تۆمارکراو لە هەرێمی کوردستان، لەسەر بنەمای متمانە بنیاتنراوە",
    brightVolitionWasFoundedIn: "برایت ڤۆلیشن لە ساڵی 2022 وەک ئۆفیسێکی ئەندازیاری پسپۆڕ لە خزمەتگوزاری کارەبایی، ئامێری پێوانە و میکانیکی دامەزرا.",
    downloadOurFullCompanyProfile: "داگرتنی پرۆفایلی تەواوی کۆمپانیا",
    ourMission: "ئەرکمان",
    toEmpowerClientsByProviding: "بەهێزکردنی کڕیارەکانمان لە ڕێگەی پێشکەشکردنی خزمەتگوزاریی ئەندازیاریی زیرەکانە، بەردەوام و کاریگەر لە ڕووی تێچووەوە کە بەهای بەردەوام بەدی دەهێنێت.",
    companyOverview: "ڕوانگەیەکی گشتی لەسەر کۆمپانیا",
    foundingVisionMilestonesFutureOutlook: "بینینی دامەزراندن، خاڵە سەرەکییەکان، و ئاواتەکانی داهاتوو",
    foundingVision: "بینینی دامەزراندن",
    leadInInnovativeSustainableAnd: "پێشەنگی لە پێشکەشکردنی چارەسەری ئەندازیاریی داهێنەرانە، بەردەوام و متمانەپێکراو.",
    empowerClientsToAchieveLasting: "بەهێزکردنی کڕیاران بۆ بەدیهێنانی باشیی بەردەوام.",
    milestones: "خاڵە سەرەکییەکان",
    incorporatedLaunchedFirstProductsService: "دامەزراندنی فەرمی و دەستپێکردنی یەکەم بەرهەم و خزمەتگوزاری.",
    broadenedOurServicesAndUpgraded: "فراوانکردنی خزمەتگوزاریەکان و بەرزکردنەوەی ئۆفیسەکە بۆ کۆمپانیایەکی بە فەرمی تۆمارکراو لە حکوومەتی هەرێمی کوردستان.",
    diversifiedServicesEnteredNewSectors: "فراوانکردنی جۆرەکانی خزمەتگوزاری و چوونە بوارە نوێیەکانەوە بە چارەسەری ئەندازیاریی پێشکەوتوو.",
    futureOutlook: "ئاواتەکانی داهاتوو",
    commitToQualitySustainabilityAnd: "پابەندبوون بە کوالیتی، بەردەوامی و بەرپرسیارێتی.",
    driveInnovationToStayAhead: "هاندانی داهێنان بۆ مانەوە لە پێشەنگیی ئاڕاستەکان.",
    expandGloballyWhileFocusingOn: "فراوانبوون لە ئاستی جیهانیدا لەگەڵ سەرنجدان لەسەر ڕازیبوونی کڕیار.",
    ourPolicy: "سیاسەتمان",
    qualityDeliveredByDesign: "کوالیتی، بە وردی داڕێژراوە",
    brightVolitionIsCommittedTo: "برایت ڤۆلیشن پابەندە بە پێشکەشکردنی چارەسەری ئەندازیاریی داهێنەرانە، بەردەوام و متمانەپێکراو، و دابینکردنی بەرهەم و خزمەتگوزاریی جێبەجێکردن کە پێداویستیەکانی کڕیار دابین دەکات و لە چاوەڕوانیەکانیان تێدەپەڕێت.",
    thisPolicyProvidesTheFramework: "ئەم سیاسەتە چوارچێوەی پێویست دابین دەکات بۆ دانان و پێداچوونەوەی ئامانجەکانی کوالیتیمان، و بۆ هەموو کارمەند و لایەنە پەیوەندیدارەکان بڵاو دەکرێتەوە بۆ دڵنیابوون لە تێگەیشتن و جێبەجێکردنی کاریگەر.",
    ensureComplianceWithLegalRegulations: "دڵنیابوون لە ڕێزگرتن لە یاساکان و ئەرکە گرێبەستییەکان.",
    striveForCustomerSatisfactionThrough: "هەوڵدان بۆ بەدیهێنانی ڕازیبوونی کڕیار لە ڕێگەی بەرهەم، خزمەتگوزاری و چارەسەری بەرزی کوالیتی.",
    fosterACultureOfContinuous: "چەسپاندنی کولتووری باشترکردنی بەردەوام لە هەموو پرۆسە، سیستەم و ئەدایەندا.",
    empowerEmployeesThroughTrainingTeamwork: "بەهێزکردنی کارمەندان لە ڕێگەی ڕاهێنان، کاری تیمی، بەرپرسیارێتی و گرنگیدان بە سەلامەتیان.",
    strengthenPartnershipsWithClientsAnd: "بەهێزکردنی هاوبەشی لەگەڵ کڕیار و دابینکەران بۆ دروستکردنی بەهای درێژخایەن.",
    howBvServesItsCustomers: "چۆن برایت ڤۆلیشن خزمەتی کڕیارەکانی دەکات",
    howWeWork: "چۆن کار دەکەین",
    confidentialityFirst: "نهێنی سەرەتا",
    wePrioritizeTheConfidentialityOf: "پێشینەیی دەدەین بە نهێنیی کڕیار و دابینکەرەکانمان، بۆ دڵنیابوون لەوەی هەموو زانیاریی هەستیار سەلامەت و پارێزراو دەمێنێتەوە.",
    streamlinedSupplyChain: "زنجیرەی دابینکردنی کاریگەر",
    efficientSupplyChainManagementGuarantees: "بەڕێوەبردنێکی کاریگەری زنجیرەی دابینکردن کە ڕادەستکردن لە کاتی دیاریکراودا دڵنیا دەکات، دواکەوتن کەم دەکاتەوە و ئەدایەن باشتر دەکات.",
    uncompromisingQualityReliability: "کوالیتی و متمانەپێکراویی بێ گوزەشت",
    wePartnerWithReputableSuppliers: "لەگەڵ دابینکەرانی متمانەپێکراو مامەڵە دەکەین بۆ دڵنیابوون لەوەی هەموو بەرهەم و خزمەتگوزارییەک بەرزترین ستانداردەکان دابین دەکات.",
    tailoredCostEffective: "چارەسەری تایبەتمەند و کاریگەر لە ڕووی تێچووەوە",
    everySolutionIsScopedAround: "هەموو چارەسەرێک بەپێی پێویستیە کارپێکراوییەکانت و بودجەکەت داڕێژراوە.",
    collaborativeApproach: "ڕێبازی هاوبەشی",
    weWorkCloselyWithClients: "لە نزیکەوە لەگەڵ کڕیاران کار دەکەین بۆ تێگەیشتن لە پێویستیەکانیان و پێشکەشکردنی باشترین چارەسەری ئەگەری.",
    commitmentToExcellence: "پابەندبوون بە باشی",
    weAreCommittedToDelivering: "ئێمە پابەندین بە پێشکەشکردنی باشی لە هەموو ئەوەی دەیکەین.",
    whyBvIsTheRight: "بۆچی برایت ڤۆلیشن هەڵبژاردەی ڕاستە",
    customerFocusInnovationResponsibility: "سەرنجدان لەسەر کڕیار، داهێنان و بەرپرسیارێتی",
    customerFocus: "سەرنجدان لەسەر کڕیار",
    wePlaceAHighValue: "گرنگیەکی زۆر دەدەین بە تێگەیشتن لە پێداویستی و ئاستەنگە تایبەتەکانی هەر کڕیارێک.",
    prioritizingExcellentServiceAndBuilding: "پێشینەیی دان بە خزمەتگوزاریی نایاب و بنیاتنانی پەیوەندیی بەهێز و درێژخایەن.",
    innovation: "داهێنان",
    weStayAheadOfThe: "بەردەوام هەنگاو بە نوێترین تەکنەلۆجیا و ئاڕاستەکانی پیشەسازی دەنێین.",
    investmentInRDEnables: "وەبەرهێنانمان لە توێژینەوە و پەرەپێدان ڕێگە بە چارەسەری پێشکەوتوو دەدات کە کارایی و بەرهەمهێنان بەهێز دەکات.",
    sustainabilitySocialResponsibility: "بەردەوامی و بەرپرسیارێتی کۆمەڵایەتی",
    offeringEnvironmentallyFriendlyEngineeri: "پێشکەشکردنی چارەسەری ئەندازیاریی دۆستی ژینگە.",
    healthSafetyRigorousStandardsFor: "تەندروستی و سەلامەتی: ستانداردی توند بۆ کرێکار، کڕیار و کۆمەڵگا.",
    energyEfficientDesignsThatReduce: "دیزاینی پاشەکەوتکەری وزە کە بەکارهێنان و دەرچوونەکان کەم دەکاتەوە.",
    csrEngagementSupportingLocalCommunities: "دەستپێشخەریی بەرپرسیارێتی کۆمەڵایەتی کە کۆمەڵگای ناوخۆیی و ژینگە پشتگیری دەکات.",
    wantToKnowMoreAbout: "دەتەوێت زیاتر لەسەر توانامان بزانیت؟",
    seeHowOurEngineeringConstruction: "بزانە چۆن توانای ئەندازیاری، جێبەجێکردن و دابینکردنمان لەگەڵ پڕۆژەی داهاتووت دەگونجێت.",
    ourServices: "خزمەتگوزاریەکانمان",
    contactUs: "پەیوەندیمان پێوە بکە",
  },
};
