// Every translated string on the contact page, one entry per key per language.
// The markup lives in contact.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    home: "Home",
    contact: "Contact",
    yourTrustedPartnerInEngineering: "Your Trusted Partner in Engineering Solutions",
    readyToCollaborate: "Ready to Collaborate?",
    reachOutWithYourInquiries: "Reach out with your inquiries or RFQs — we’re here to deliver precision, quality, and trust.",
    contactDetails: "Contact Details",
    email2: "Email",
    phone: "Phone",
    address: "Address",
    mardinStreetOppositeDilanCity: "Mardin Street, Opposite Dilan City, Sulaymaniyah (46001), Iraq",
    coverage: "Coverage",
    kurdistanRegionIraq: "Kurdistan Region & Iraq",
    website: "Website",
    supplyChainTeam: "Supply Chain Team",
    technicalTeam: "Technical Team",
    email3: "Email",
    findUs: "Find Us",
    sulaymaniyahKurdistanRegionOfIraq: "Sulaymaniyah, Kurdistan Region of Iraq",
    form: {
      heading: "Send an Inquiry or RFQ",
      intro: "Fill in the form and it will open a pre-filled email to our team.",
      name: "Full Name",
      email: "Email",
      subject: "Subject",
      subjectPlaceholder: "RFQ, project inquiry, partnership...",
      message: "Message",
      send: "Send Message",
      defaultSubject: "Website enquiry",
      note: "Your email app should now be open with your message ready to send. If it didn’t open, please email us directly at info@brightvolition.com.",
    },
  },
  ar: {
    home: "الرئيسية",
    contact: "تواصل معنا",
    yourTrustedPartnerInEngineering: "شريككم الموثوق في الحلول الهندسية",
    readyToCollaborate: "مستعد للتعاون؟",
    reachOutWithYourInquiries: "تواصل معنا لأي استفسار أو طلب عرض سعر — نحن هنا لنقدّم لك الدقة والجودة والثقة.",
    contactDetails: "معلومات التواصل",
    email2: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    mardinStreetOppositeDilanCity: "شارع ماردين، مقابل مدينة دلان، السليمانية (46001)، العراق",
    coverage: "نطاق العمل",
    kurdistanRegionIraq: "إقليم كوردستان والعراق",
    website: "الموقع الإلكتروني",
    supplyChainTeam: "فريق سلسلة التوريد",
    technicalTeam: "الفريق الفني",
    email3: "البريد الإلكتروني",
    findUs: "موقعنا",
    sulaymaniyahKurdistanRegionOfIraq: "السليمانية، إقليم كوردستان العراق",
    form: {
      heading: "أرسل استفسارًا أو طلب عرض سعر",
      intro: "املأ النموذج وسيتم فتح رسالة بريد إلكتروني معبأة مسبقًا لفريقنا.",
      name: "الاسم الكامل",
      email: "البريد الإلكتروني",
      subject: "الموضوع",
      subjectPlaceholder: "طلب عرض سعر، استفسار عن مشروع، شراكة...",
      message: "الرسالة",
      send: "إرسال الرسالة",
      defaultSubject: "استفسار من الموقع",
      note: "من المفترض أن يكون تطبيق البريد الإلكتروني قد فُتح برسالتك جاهزة للإرسال. إذا لم يفتح، الرجاء مراسلتنا مباشرة على info@brightvolition.com.",
    },
  },
  ku: {
    home: "سەرەکی",
    contact: "پەیوەندیمان پێوە بکە",
    yourTrustedPartnerInEngineering: "هاوبەشی متمانەپێکراوتان لە چارەسەری ئەندازیاریدا",
    readyToCollaborate: "ئامادەیت بۆ هاوکاری؟",
    reachOutWithYourInquiries: "پەیوەندیمان پێوە بکە بۆ هەر پرسیارێک یان داواکاری نرخنامە — ئێمە لێرەین بۆ پێشکەشکردنی وردی، کوالیتی و متمانە بۆت.",
    contactDetails: "زانیاریی پەیوەندی",
    email2: "ئیمەیل",
    phone: "تەلەفۆن",
    address: "ناونیشان",
    mardinStreetOppositeDilanCity: "شەقامی ماردین، بەرامبەر شاری دیلان، سلێمانی (46001)، عێراق",
    coverage: "مەودای کار",
    kurdistanRegionIraq: "هەرێمی کوردستان و عێراق",
    website: "ماڵپەڕ",
    supplyChainTeam: "تیمی زنجیرەی دابینکردن",
    technicalTeam: "تیمی تەکنیکی",
    email3: "ئیمەیل",
    findUs: "شوێنمان",
    sulaymaniyahKurdistanRegionOfIraq: "سلێمانی، هەرێمی کوردستانی عێراق",
    form: {
      heading: "پرسیارێک یان داواکاری نرخنامە بنێرە",
      intro: "فۆرمەکە پڕبکەرەوە و نامەیەکی ئیمەیلی پێشپڕکراو بۆ تیمەکەمان دەکرێتەوە.",
      name: "ناوی تەواو",
      email: "ئیمەیل",
      subject: "بابەت",
      subjectPlaceholder: "داواکاری نرخنامە، پرسیار دەربارەی پڕۆژە، هاوبەشی...",
      message: "پەیام",
      send: "ناردنی پەیام",
      defaultSubject: "پرسیار لە ماڵپەڕەوە",
      note: "دەبێت ئەپی ئیمەیل بە پەیامەکەت ئامادە بۆ ناردن کرابێتەوە. ئەگەر نەکرایەوە، تکایە ڕاستەوخۆ لە info@brightvolition.com پەیوەندیمان پێوە بکە.",
    },
  },
};
