// Every translated string on the home page, one entry per key per language.
// The markup lives in index.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    industrialSupplyEngineeringServices: "Industrial Supply & Engineering Services",
    brightVolitionDeliversElectricalInstrume: "Bright Volition delivers Electrical, Instrumentation & Mechanical engineering, construction, commissioning, and product supply — from feasibility study through to operations support.",
    exploreOurServices: "Explore Our Services",
    talkToOurTeam: "Talk to Our Team",
    whatWeDo: "What We Do",
    fiveWaysWeDeliverEngineering: "Five Ways We Deliver Engineering Excellence",
    deliveringSpecializedEngineeringServices: "Delivering specialized engineering services alongside reliable supply of electrical, mechanical, and instrumentation systems.",
    designEngineering: "Design & Engineering",
    feasibilityStudiesConceptualDesignAnd: "Feasibility studies, conceptual design, and detailed electrical, mechanical & instrumentation engineering.",
    constructionInstallation: "Construction & Installation",
    fullFieldExecutionAcrossElectrical: "Full field execution across electrical, mechanical, and instrumentation systems, built to spec.",
    systemCommissioningStartUp: "System Commissioning & Start-Up",
    structuredPreCommissioningTestingAnd: "Structured pre-commissioning, testing, and start-up support for a smooth handover.",
    productSupplySourcing: "Product Supply & Sourcing",
    electricalInstrumentationMechanicalCompo: "Electrical, instrumentation & mechanical components sourced from trusted global manufacturers.",
    operationsSupportTroubleshooting: "Operations Support & Troubleshooting",
    rootCauseAnalysisAndRapid: "Root-cause analysis and rapid response that minimizes downtime and protects reliability.",
    whoWeAre: "Who We Are",
    engineeringLedClientFocusedBuilt: "Engineering-Led. Client-Focused. Built in the Kurdistan Region.",
    brightVolitionWasFoundedIn: "Bright Volition was founded in 2022 as an engineering office specializing in Electrical, Instrumentation, and Mechanical services. Since then we’ve incorporated, become a registered KRG company, and diversified into new sectors — always guided by a strict quality policy.",
    leadInInnovativeSustainableReliable: "Lead in innovative, sustainable, reliable engineering",
    registeredKrgCompanyWithA: "Registered KRG company with a strict quality policy",
    confidentialTailoredAndCostEffective: "Confidential, tailored, and cost-effective solutions",
    moreAboutUs: "More About Us",
    n2025ModelProject: "2025 Model Project",
    reliabilityGridImpactStudyFor: "Reliability & Grid-Impact Study for a 50MW Solar Power Plant",
    forSinomaDccLine2: "For Sinoma DCC Line 2 / Delta Cement Company in Bazyan, Sulaymaniyah, we delivered a full power-system impact study — coordinated directly with Iraq’s Ministry of Electricity.",
    dcSolarPlantStudied: "DC solar plant studied",
    toolsPssEPscadEtap: "Tools: PSS®E · PSCAD · ETAP",
    monthsOfEngineeringScope: "Months of engineering scope",
    viewProjectDetails: "View Project Details",
    whyBrightVolition: "Why Bright Volition",
    aPartnerThatServesYou: "A Partner That Serves You Right",
    confidentialityFirst: "Confidentiality First",
    sensitiveClientAndSupplierInformation: "Sensitive client and supplier information stays secure and protected, always.",
    tailoredCostEffective: "Tailored & Cost-Effective",
    solutionsScopedToYourExact: "Solutions scoped to your exact requirements — never one-size-fits-all.",
    collaborativeApproach: "Collaborative Approach",
    weWorkCloselyWithClients: "We work closely with clients to understand needs and co-create the best solution.",
    streamlinedSupplyChain: "Streamlined Supply Chain",
    efficientLogisticsThatMinimizeDelays: "Efficient logistics that minimize delays and keep your project on schedule.",
    uncompromisingQuality: "Uncompromising Quality",
    wePartnerOnlyWithReputable: "We partner only with reputable suppliers so every solution meets the highest standard.",
    innovationDriven: "Innovation-Driven",
    investmentInRDKeeps: "Investment in R&D keeps us ahead of trends, offering cutting-edge solutions.",
    brandsWeRepresent: "Brands We Represent",
    someOfOurClients: "Some of Our Clients",
    readyToCollaborate: "Ready to Collaborate?",
    letSBuildSomethingReliable: "Let’s Build Something Reliable Together",
    reachOutWithYourInquiries: "Reach out with your inquiries or RFQs — we’re here to deliver precision, quality, and trust.",
    contactUs: "Contact Us",
  },
  ar: {
    industrialSupplyEngineeringServices: "التوريد الصناعي والخدمات الهندسية",
    brightVolitionDeliversElectricalInstrume: "تقدّم الإرادة المشرقة خدمات الهندسة الكهربائية وأجهزة القياس والميكانيكية، إلى جانب التنفيذ والتشغيل والتوريد — من دراسة الجدوى وحتى دعم التشغيل.",
    exploreOurServices: "استكشف خدماتنا",
    talkToOurTeam: "تواصل مع فريقنا",
    whatWeDo: "ماذا نقدّم",
    fiveWaysWeDeliverEngineering: "خمسة محاور نقدّم من خلالها التميّز الهندسي",
    deliveringSpecializedEngineeringServices: "نقدّم خدمات هندسية متخصصة إلى جانب توريد موثوق لأنظمة كهربائية وميكانيكية وأجهزة قياس.",
    designEngineering: "التصميم والهندسة",
    feasibilityStudiesConceptualDesignAnd: "دراسات جدوى، تصميم مفاهيمي، وهندسة تفصيلية كهربائية وميكانيكية وأجهزة قياس.",
    constructionInstallation: "التنفيذ والتركيب",
    fullFieldExecutionAcrossElectrical: "تنفيذ ميداني كامل للأنظمة الكهربائية والميكانيكية وأجهزة القياس وفق المواصفات.",
    systemCommissioningStartUp: "التشغيل التجريبي والانطلاق",
    structuredPreCommissioningTestingAnd: "تحضير قبل التشغيل واختبارات ودعم الانطلاق لضمان تسليم سلس.",
    productSupplySourcing: "توريد المنتجات",
    electricalInstrumentationMechanicalCompo: "مكونات كهربائية وأجهزة قياس وميكانيكية موثوقة من كبرى الشركات العالمية.",
    operationsSupportTroubleshooting: "دعم التشغيل واستكشاف الأعطال",
    rootCauseAnalysisAndRapid: "تحليل الأسباب الجذرية واستجابة سريعة لتقليل التوقف والحفاظ على الموثوقية.",
    whoWeAre: "من نحن",
    engineeringLedClientFocusedBuilt: "هندسة أصيلة، تركيز على العميل، انطلاقًا من إقليم كوردستان.",
    brightVolitionWasFoundedIn: "تأسست الإرادة المشرقة عام 2022 كمكتب هندسي متخصص بالخدمات الكهربائية وأجهزة القياس والميكانيكية. ومنذ ذلك الحين تم تأسيسها رسميًا، وأصبحت شركة مسجلة في حكومة إقليم كوردستان، ووسّعت نشاطها إلى قطاعات جديدة — مسترشدة دومًا بسياسة جودة صارمة.",
    leadInInnovativeSustainableReliable: "الريادة في هندسة مبتكرة ومستدامة وموثوقة",
    registeredKrgCompanyWithA: "شركة مسجّلة رسميًا وسياسة جودة صارمة",
    confidentialTailoredAndCostEffective: "حلول سرّية ومخصصة وفعّالة من حيث التكلفة",
    moreAboutUs: "المزيد عنّا",
    n2025ModelProject: "مشروع نموذجي 2025",
    reliabilityGridImpactStudyFor: "دراسة الموثوقية والتأثير الشبكي لمحطة طاقة شمسية بقدرة 50 ميغاواط",
    forSinomaDccLine2: "قمنا بتنفيذ دراسة شاملة لتأثير النظام الكهربائي لصالح خط سينوما دي سي سي 2 التابع لشركة دلتا للإسمنت في بازيان، السليمانية — بالتنسيق المباشر مع وزارة الكهرباء العراقية.",
    dcSolarPlantStudied: "محطة شمسية بقدرة 50 ميغاواط",
    toolsPssEPscadEtap: "أدوات: PSS®E · PSCAD · ETAP",
    monthsOfEngineeringScope: "أشهر من العمل الهندسي",
    viewProjectDetails: "عرض تفاصيل المشروع",
    whyBrightVolition: "لماذا الإرادة المشرقة",
    aPartnerThatServesYou: "شريك يخدمك بالشكل الصحيح",
    confidentialityFirst: "السرّية أولًا",
    sensitiveClientAndSupplierInformation: "نحافظ على أمن وسرّية معلومات العملاء والموردين في كل الأوقات.",
    tailoredCostEffective: "حلول مخصصة وفعّالة من حيث التكلفة",
    solutionsScopedToYourExact: "حلول مصممة خصيصًا لاحتياجاتك — دون قوالب جاهزة.",
    collaborativeApproach: "نهج تعاوني",
    weWorkCloselyWithClients: "نعمل عن قرب مع العملاء لفهم احتياجاتهم وابتكار الحل الأنسب معًا.",
    streamlinedSupplyChain: "سلسلة توريد فعّالة",
    efficientLogisticsThatMinimizeDelays: "لوجستيات فعّالة تقلل التأخير وتحافظ على جدول مشروعك.",
    uncompromisingQuality: "جودة لا تقبل التنازل",
    wePartnerOnlyWithReputable: "نتعامل فقط مع موردين موثوقين لضمان أعلى المعايير في كل حل.",
    innovationDriven: "مدفوعة بالابتكار",
    investmentInRDKeeps: "استثمارنا في البحث والتطوير يبقينا في صدارة التوجهات بحلول متطورة.",
    brandsWeRepresent: "العلامات التجارية التي نمثلها",
    someOfOurClients: "بعض من عملائنا",
    readyToCollaborate: "مستعد للتعاون؟",
    letSBuildSomethingReliable: "لنبنِ معًا شيئًا موثوقًا",
    reachOutWithYourInquiries: "تواصل معنا لأي استفسار أو طلب عرض سعر — نحن هنا لنقدّم لك الدقة والجودة والثقة.",
    contactUs: "تواصل معنا",
  },
  ku: {
    industrialSupplyEngineeringServices: "دابینکردنی پیشەسازی و خزمەتگوزاریی ئەندازیاری",
    brightVolitionDeliversElectricalInstrume: "برایت ڤۆلیشن خزمەتگوزاری ئەندازیاری کارەبا، ئامێری پێوانە و میکانیک پێشکەش دەکات، لەگەڵ جێبەجێکردن، بەکارخستن و دابینکردنیش — لە خوێندنەوەی گونجاویدا تا پشتگیری کارپێکردن.",
    exploreOurServices: "خزمەتگوزاریەکانمان ببینە",
    talkToOurTeam: "پەیوەندی بە تیمەکەمانەوە بکە",
    whatWeDo: "چیمان پێشکەشە",
    fiveWaysWeDeliverEngineering: "پێنج ڕێگا کە تیایاندا باشیی ئەندازیاری پێشکەش دەکەین",
    deliveringSpecializedEngineeringServices: "خزمەتگوزاری ئەندازیاری پسپۆڕانە پێشکەش دەکەین لەگەڵ دابینکردنی متمانەپێکراوی سیستەمی کارەبایی، میکانیکی و ئامێری پێوانە.",
    designEngineering: "دیزاین و ئەندازیاری",
    feasibilityStudiesConceptualDesignAnd: "خوێندنەوەی گونجاوی، دیزاینی چەمکی، و ئەندازیاری وردی کارەبایی، میکانیکی و ئامێری پێوانە.",
    constructionInstallation: "جێبەجێکردن و دامەزراندن",
    fullFieldExecutionAcrossElectrical: "جێبەجێکردنی تەواوی مەیدانی بۆ سیستەمی کارەبایی، میکانیکی و ئامێری پێوانە بەپێی ڕێنماییەکان.",
    systemCommissioningStartUp: "کارپێکردنی تاقیکارییانە و دەستپێکردن",
    structuredPreCommissioningTestingAnd: "ئامادەکاری پێش کارپێکردن، تاقیکردنەوە و پشتگیری دەستپێکردن بۆ دڵنیابوون لە ڕادەستکردنێکی ئاسان.",
    productSupplySourcing: "دابینکردنی بەرهەم",
    electricalInstrumentationMechanicalCompo: "پێکهاتەی کارەبایی، ئامێری پێوانە و میکانیکی متمانەپێکراو لە گەورەترین کۆمپانیا جیهانییەکان.",
    operationsSupportTroubleshooting: "پشتگیری کارپێکردن و شیکردنەوەی کێشە",
    rootCauseAnalysisAndRapid: "شیکردنەوەی هۆکاری بنەڕەتی و وەڵامدانەوەیەکی خێرا بۆ کەمکردنەوەی وەستان و پاراستنی متمانەپێکراوی.",
    whoWeAre: "دەربارەمان",
    engineeringLedClientFocusedBuilt: "ئەندازیارییەکی ڕەسەن، سەرنجدان لەسەر کڕیار، هەڵگیرساوە لە هەرێمی کوردستانەوە.",
    brightVolitionWasFoundedIn: "برایت ڤۆلیشن لە ساڵی 2022 وەک ئۆفیسێکی ئەندازیاری پسپۆڕ لە خزمەتگوزاری کارەبایی، ئامێری پێوانە و میکانیکی دامەزرا. لەو کاتەوە بە فەرمی تۆمار کرا و بوو بە کۆمپانیایەکی تۆمارکراو لە حکوومەتی هەرێمی کوردستان، و چالاکیی خۆی بۆ بوارە نوێیەکانیش فراوان کرد — هەمیشە بە ڕێنمایی سیاسەتی کوالیتیی توند.",
    leadInInnovativeSustainableReliable: "پێشەنگی لە ئەندازیاریی داهێنەرانە، بەردەوام و متمانەپێکراودا",
    registeredKrgCompanyWithA: "کۆمپانیایەکی بە فەرمی تۆمارکراو و سیاسەتی کوالیتیی توند",
    confidentialTailoredAndCostEffective: "چارەسەری نهێنی، تایبەتمەند و کاریگەر لە ڕووی تێچووەوە",
    moreAboutUs: "زیاتر دەربارەمان",
    n2025ModelProject: "پڕۆژەی نموونەیی 2025",
    reliabilityGridImpactStudyFor: "خوێندنەوەی متمانەپێکراوی و کاریگەری گرید بۆ وێستگەیەکی وزەی خۆر بە توانای 50 مێگاوات",
    forSinomaDccLine2: "خوێندنەوەیەکی گشتگیرمان بۆ کاریگەری سیستەمی کارەبایی بۆ هێڵی سینۆما دی سی سی 2ی کۆمپانیای دێلتا سیمێنت لە بازیان، سلێمانی جێبەجێ کرد — بە هاوکاریی ڕاستەوخۆ لەگەڵ وەزارەتی کارەبای عێراق.",
    dcSolarPlantStudied: "وێستگەی خۆر بە توانای 50 مێگاوات",
    toolsPssEPscadEtap: "ئامرازەکان: PSS®E · PSCAD · ETAP",
    monthsOfEngineeringScope: "مانگی کاری ئەندازیاری",
    viewProjectDetails: "وردەکاریی پڕۆژە ببینە",
    whyBrightVolition: "بۆچی برایت ڤۆلیشن",
    aPartnerThatServesYou: "هاوبەشێک بە شێوەی ڕاست خزمەتت دەکات",
    confidentialityFirst: "نهێنی سەرەتا",
    sensitiveClientAndSupplierInformation: "لە هەموو کاتێکدا ئاسایش و نهێنیی زانیاریی کڕیار و دابینکەران دەپارێزین.",
    tailoredCostEffective: "چارەسەری تایبەتمەند و کاریگەر لە ڕووی تێچووەوە",
    solutionsScopedToYourExact: "چارەسەرێک تایبەت بۆ پێویستیەکانت داڕێژراوە — بێ قاڵبی ئامادە.",
    collaborativeApproach: "ڕێبازی هاوبەشی",
    weWorkCloselyWithClients: "لە نزیکەوە لەگەڵ کڕیاران کار دەکەین بۆ تێگەیشتن لە پێویستیەکانیان و پێکەوە داهێنانی گونجاوترین چارەسەر.",
    streamlinedSupplyChain: "زنجیرەی دابینکردنی کاریگەر",
    efficientLogisticsThatMinimizeDelays: "لۆجستیکی کاریگەر کە دواکەوتن کەم دەکاتەوە و خشتەی پڕۆژەکەت دەپارێزێت.",
    uncompromisingQuality: "کوالیتیی بێ گوزەشت",
    wePartnerOnlyWithReputable: "تەنها لەگەڵ دابینکەرانی متمانەپێکراو مامەڵە دەکەین بۆ دڵنیابوون لە بەرزترین ستاندارد لە هەموو چارەسەرێکدا.",
    innovationDriven: "لە ڕێگەی داهێنانەوە هاندراو",
    investmentInRDKeeps: "وەبەرهێنانمان لە توێژینەوە و پەرەپێدان ئێمە لە پێشەنگیی ئاڕاستەکان ڕادەگرێت بە چارەسەری پێشکەوتوو.",
    brandsWeRepresent: "براندە بازرگانییەکانی نوێنەرایەتیمان دەکەین",
    someOfOurClients: "هەندێک لە کڕیارەکانمان",
    readyToCollaborate: "ئامادەیت بۆ هاوکاری؟",
    letSBuildSomethingReliable: "با پێکەوە شتێکی متمانەپێکراو بنیات بنێین",
    reachOutWithYourInquiries: "پەیوەندیمان پێوە بکە بۆ هەر پرسیارێک یان داواکاری نرخنامە — ئێمە لێرەین بۆ پێشکەشکردنی وردی، کوالیتی و متمانە بۆت.",
    contactUs: "پەیوەندیمان پێوە بکە",
  },
};
