// Every translated string on the products page, one entry per key per language.
// The markup lives in products.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    home: "Home",
    products: "Products",
    productSupplySourcing: "Product Supply & Sourcing",
    aCompleteRangeOfElectrical: "A Complete Range of Electrical, Instrument & Mechanical Products",
    weSupplyComponentsSystemsAnd: "We supply components, systems, and precision instruments — partnering with the world’s leading manufacturers to ensure reliability and accuracy from energy source to end-use.",
    electrical: "Electrical",
    instrumentation: "Instrumentation",
    mechanical: "Mechanical",
    productSupply: "Product Supply",
    electrical2: "Electrical",
    switchgearPanelComponents: "Switchgear & Panel Components",
    mccbMcbRcdContactorsOverload: "MCCB, MCB, RCD, contactors, overload relays, motor starters (DOL, Star-Delta).",
    controlPanels: "Control Panels",
    lvControlPanelsPlcPanels: "LV control panels, PLC panels, MCC panels.",
    controlSignalingDevices: "Control & Signaling Devices",
    pushButtonsSelectorSwitchesIndicator: "Push buttons, selector switches, indicator lamps, timers, phase monitoring relays.",
    backupCriticalPower: "Backup & Critical Power",
    uninterruptiblePowerSuppliesUpsBattery: "Uninterruptible power supplies (UPS), battery banks, generators.",
    powerConditioning: "Power Conditioning",
    voltageRegulatorsRectifiersControlTransf: "Voltage regulators, rectifiers, control transformers.",
    solarEnergySolutions: "Solar Energy Solutions",
    invertersChargeControllersSolarPanels: "Inverters, charge controllers, solar panels, and balance of system (BOS) components.",
    motors: "Motors",
    acDcMotorsLvHv: "AC/DC motors (LV & HV).",
    motorControlEfficiency: "Motor Control & Efficiency",
    variableSpeedDrivesVsdSoft: "Variable speed drives (VSD), soft starters.",
    cables: "Cables",
    powerCableLvMvHv: "Power cable (LV, MV, HV), instrumentation & control cable, data cable.",
    earthingGroundingSystems: "Earthing / Grounding Systems",
    earthRodsEarthCableEarth: "Earth rods, earth cable, earth bars, clamps, bentonite compound.",
    cableManagement: "Cable Management",
    cableTraysLaddersConduitsAnd: "Cable trays, ladders, conduits, and junction boxes.",
    heatTraceSystems: "Heat Trace Systems",
    htPanelsHeatingCablesJunction: "HT panels, heating cables, junction boxes, splice kits, controllers, monitoring RTDs.",
    lightingSolutions: "Lighting Solutions",
    ledHidMetalHalideHigh: "LED, HID (metal halide, high-pressure sodium), fluorescent, Ex-proof fixtures, emergency lighting, floodlights.",
    powerEquipment: "Power Equipment",
    distributionTransformersProtectiveRelays: "Distribution transformers, protective relays, circuit breakers.",
    testMeasurement: "Test & Measurement",
    multimetersClampMetersInsulationTesters: "Multimeters, clamp meters, insulation testers, power quality analyzers, energy meters, data loggers, oscilloscopes.",
    productSupply2: "Product Supply",
    instrument: "Instrument",
    aCompleteRangeOfPrecision: "A complete range of precision instruments for measurement, control, and safety, partnering with the world’s leading manufacturers to ensure reliability and accuracy.",
    temperature: "Temperature",
    rtdsThermocouplesTemperatureTransmitters: "RTDs, thermocouples, temperature transmitters & gauges.",
    pressure: "Pressure",
    pressureGaugesTransmittersTransducersSwi: "Pressure gauges, transmitters, transducers, switches & digital indicators.",
    flow: "Flow",
    dpFlowMetersMagneticVortex: "DP flow meters, magnetic, vortex, ultrasonic, turbine & Coriolis mass flow meters.",
    level: "Level",
    levelTransmittersRadarUltrasonicSwitches: "Level transmitters (radar, ultrasonic), switches, sight glasses & indicators.",
    gasProcessAnalysis: "Gas & Process Analysis",
    oxygenInfraredIrLaserGas: "Oxygen, infrared (IR), laser gas analyzers & pH/conductivity sensors.",
    controlValvesActuators: "Control Valves & Actuators",
    pneumaticAndElectricControlValves: "Pneumatic and electric control valves & actuators.",
    manifoldInstrumentValves: "Manifold & Instrument Valves",
    manifoldValves235: "Manifold valves (2, 3 & 5-valve), needle valves, check valves, and ball valves.",
    fireGasDetectionFG: "Fire & Gas Detection (F&G)",
    fireAlarmControlPanelsSmoke: "Fire alarm control panels, smoke/heat/combustible gas detectors, manual call points, sounders & flashers.",
    processSafety: "Process Safety",
    pressureSafetyValvesPsvSwitches: "Pressure safety valves (PSV), switches, and emergency shutdown (ESD) components.",
    controlSystemComponents: "Control System Components",
    processControllersSignalConditionersAnd: "Process controllers, signal conditioners, and PLC I/O modules.",
    instrumentationCablingAccessories: "Instrumentation Cabling & Accessories",
    instrumentationCablingJunctionBoxesAnd: "Instrumentation cabling, junction boxes, and intrinsic safety barriers.",
    productSupply3: "Product Supply",
    mechanical2: "Mechanical",
    pipingValvesFittings: "Piping, Valves & Fittings",
    pipesTubesFittingsFlangesElbows: "Pipes, tubes & fittings (flanges, elbows, tees, reducers, couplings, unions, adapters, caps, nipples); industrial valves (gate, globe, check, ball, butterfly); gaskets, O-rings, mechanical seals & industrial sealants.",
    powerTransmissionMotionControl: "Power Transmission & Motion Control",
    ballRollerLinearBearingsFrom: "Ball, roller & linear bearings from leading brands; V-belts, timing belts, flat belts, multi-ribbed belts, pulleys; chains, sprockets & couplings.",
    rotatingEquipmentSupport: "Rotating Equipment & Support",
    pumpsCompressorsFansBlowersTurbines: "Pumps, compressors, fans, blowers, turbines, genuine spare parts, industrial lubricants & automatic lubrication systems.",
    hvacClimateControl: "HVAC & Climate Control",
    hvacAndVrfSystemComponents: "HVAC and VRF system components & spare parts; commercial and industrial heating — radiators, boilers, components.",
    fabricationConstructionStructural: "Fabrication, Construction & Structural",
    weldingConsumablesElectrodesWiresGases: "Welding consumables (electrodes, wires, gases) & equipment; metal cutting & machining supplies; structural steel — channels, I-beams, angles, plates.",
    fasteningAssembly: "Fastening & Assembly",
    boltsScrewsNutsWashersStuds: "Bolts, screws, nuts, washers, studs; construction fasteners — nails, anchors, rivets.",
    filtrationFluidConditioning: "Filtration & Fluid Conditioning",
    hydraulicFiltersAirFiltersOil: "Hydraulic filters, air filters, oil filters, and strainers; material handling — conveyor belts, idlers, and components.",
    trustedManufacturers: "Trusted Manufacturers",
    brandsWeRepresent: "Brands We Represent",
    weSourceFromGloballyRecognized: "We source from globally recognized manufacturers to keep every project reliable.",
    someOfOurClients: "Some of Our Clients",
    whySourceFromUs: "Why Source From Us",
    ourSupplyPromise: "Our Supply Promise",
    productsSourcedFromGloballyCertified: "Products sourced from globally certified manufacturers",
    deliveredWithFullDocumentationAnd: "Delivered with full documentation and compliance testing",
    fastTurnaroundAndTechnicalSupport: "Fast turnaround and technical support",
    integrationReadyWithProjectEngineering: "Integration-ready with project engineering services",
    lookingForASpecificComponent: "Looking for a Specific Component?",
    sendUsYourBoqOr: "Send us your BOQ or spec sheet and we’ll source it — reliably, and at the right price.",
    requestAQuote: "Request a Quote",
    ourServices: "Our Services",
  },
  ar: {
    home: "الرئيسية",
    products: "منتجاتنا",
    productSupplySourcing: "توريد المنتجات",
    aCompleteRangeOfElectrical: "مجموعة متكاملة من المنتجات الكهربائية وأجهزة القياس والميكانيكية",
    weSupplyComponentsSystemsAnd: "نوفر مكونات وأنظمة وأجهزة قياس دقيقة — بالشراكة مع كبرى الشركات المصنّعة العالمية لضمان الموثوقية والدقة من مصدر الطاقة وحتى نقطة الاستخدام.",
    electrical: "كهربائي",
    instrumentation: "أجهزة قياس",
    mechanical: "ميكانيكي",
    productSupply: "توريد المنتجات",
    electrical2: "كهربائي",
    switchgearPanelComponents: "مكونات لوحات المفاتيح الكهربائية",
    mccbMcbRcdContactorsOverload: "قواطع MCCB، MCB، RCD، كونتاكتورات، مرحلات حماية من الحمل الزائد، مشغلات محركات (مباشر ونجمة-مثلث).",
    controlPanels: "لوحات التحكم",
    lvControlPanelsPlcPanels: "لوحات تحكم منخفضة الجهد، لوحات PLC، لوحات MCC.",
    controlSignalingDevices: "أجهزة التحكم والإشارة",
    pushButtonsSelectorSwitchesIndicator: "أزرار ضغط، مفاتيح اختيار، مصابيح مؤشرة، مؤقتات، مرحلات مراقبة الطور.",
    backupCriticalPower: "الطاقة الاحتياطية والحرجة",
    uninterruptiblePowerSuppliesUpsBattery: "مزودات طاقة غير منقطعة (UPS)، بنوك بطاريات، مولدات.",
    powerConditioning: "تكييف الطاقة",
    voltageRegulatorsRectifiersControlTransf: "منظمات الجهد، مقومات، محولات تحكم.",
    solarEnergySolutions: "حلول الطاقة الشمسية",
    invertersChargeControllersSolarPanels: "عاكسات، منظمات شحن، ألواح شمسية، ومكونات توازن النظام (BOS).",
    motors: "المحركات",
    acDcMotorsLvHv: "محركات تيار متردد ومستمر (منخفضة وعالية الجهد).",
    motorControlEfficiency: "تحكم وكفاءة المحركات",
    variableSpeedDrivesVsdSoft: "محركات سرعة متغيرة (VSD)، مشغلات ناعمة.",
    cables: "الكابلات",
    powerCableLvMvHv: "كابلات طاقة (منخفضة، متوسطة، عالية الجهد)، كابلات تحكم وقياس، كابلات بيانات.",
    earthingGroundingSystems: "أنظمة التأريض",
    earthRodsEarthCableEarth: "قضبان تأريض، كابلات تأريض، قضبان توصيل، مشابك، مركب البنتونايت.",
    cableManagement: "إدارة الكابلات",
    cableTraysLaddersConduitsAnd: "مجاري كابلات، سلالم، أنابيب حماية، وصناديق توصيل.",
    heatTraceSystems: "أنظمة التسخين المرافق",
    htPanelsHeatingCablesJunction: "لوحات HT، كابلات تسخين، صناديق توصيل، أطقم وصل، وحدات تحكم، أجهزة استشعار RTD.",
    lightingSolutions: "حلول الإنارة",
    ledHidMetalHalideHigh: "إنارة LED، HID، فلورسنت، تجهيزات مقاومة للانفجار، إنارة طوارئ، كشافات.",
    powerEquipment: "معدات الطاقة",
    distributionTransformersProtectiveRelays: "محولات توزيع، مرحلات حماية، قواطع دائرة.",
    testMeasurement: "الفحص والقياس",
    multimetersClampMetersInsulationTesters: "أجهزة قياس متعددة، ملزمات قياس، فاحصات عزل، محللات جودة الطاقة، عدادات طاقة، مسجلات بيانات، راسمات إشارة.",
    productSupply2: "توريد المنتجات",
    instrument: "أجهزة القياس",
    aCompleteRangeOfPrecision: "مجموعة متكاملة من أجهزة القياس الدقيقة للقياس والتحكم والسلامة، بالشراكة مع كبرى الشركات المصنّعة العالمية لضمان الموثوقية والدقة.",
    temperature: "الحرارة",
    rtdsThermocouplesTemperatureTransmitters: "أجهزة RTD، مزدوجات حرارية، أجهزة إرسال ومقاييس حرارة.",
    pressure: "الضغط",
    pressureGaugesTransmittersTransducersSwi: "مقاييس ضغط، أجهزة إرسال، محولات، مفاتيح ومؤشرات رقمية.",
    flow: "التدفق",
    dpFlowMetersMagneticVortex: "مقاييس تدفق فرق الضغط، مغناطيسية، دوامية، فوق صوتية، توربينية وكوريوليس.",
    level: "المستوى",
    levelTransmittersRadarUltrasonicSwitches: "أجهزة إرسال مستوى (رادار، فوق صوتي)، مفاتيح، زجاج معاينة ومؤشرات.",
    gasProcessAnalysis: "تحليل الغاز والعمليات",
    oxygenInfraredIrLaserGas: "محللات أكسجين، أشعة تحت حمراء، تحليل الغاز بالليزر، وحساسات pH/الموصلية.",
    controlValvesActuators: "صمامات وحركات التحكم",
    pneumaticAndElectricControlValves: "صمامات ومشغلات تحكم هوائية وكهربائية.",
    manifoldInstrumentValves: "صمامات المانيفولد والأجهزة",
    manifoldValves235: "صمامات مانيفولد (2، 3، 5 صمام)، صمامات إبرة، صمامات فحص، صمامات كروية.",
    fireGasDetectionFG: "كشف الحريق والغاز",
    fireAlarmControlPanelsSmoke: "لوحات تحكم بإنذار الحريق، كواشف دخان وحرارة وغاز، نقاط استدعاء يدوية، أجهزة إنذار صوتي وضوئي.",
    processSafety: "سلامة العمليات",
    pressureSafetyValvesPsvSwitches: "صمامات أمان الضغط (PSV)، مفاتيح، ومكونات الإيقاف الطارئ (ESD).",
    controlSystemComponents: "مكونات أنظمة التحكم",
    processControllersSignalConditionersAnd: "وحدات تحكم بالعمليات، مكيّفات إشارة، ووحدات إدخال/إخراج PLC.",
    instrumentationCablingAccessories: "كابلات وملحقات الأجهزة",
    instrumentationCablingJunctionBoxesAnd: "كابلات أجهزة القياس، صناديق توصيل، وحواجز السلامة الجوهرية.",
    productSupply3: "توريد المنتجات",
    mechanical2: "ميكانيكي",
    pipingValvesFittings: "الأنابيب والصمامات والتجهيزات",
    pipesTubesFittingsFlangesElbows: "أنابيب وتجهيزات (فلنجات، أكواع، تيات، مخفضات، وصلات)؛ صمامات صناعية (بوابة، كروية، فحص، فراشة)؛ حشوات، حلقات O، وسدادات ميكانيكية.",
    powerTransmissionMotionControl: "نقل القدرة والتحكم الحركي",
    ballRollerLinearBearingsFrom: "محامل كروية، دحرجة وخطية من علامات رائدة؛ أحزمة V، أحزمة توقيت، سلاسل، تروس وقارنات.",
    rotatingEquipmentSupport: "المعدات الدوّارة والدعم",
    pumpsCompressorsFansBlowersTurbines: "مضخات، ضواغط، مراوح، نفاخات، توربينات، قطع غيار أصلية، مزلقات صناعية وأنظمة تشحيم أوتوماتيكية.",
    hvacClimateControl: "التكييف والتحكم بالمناخ",
    hvacAndVrfSystemComponents: "مكونات وقطع غيار أنظمة التكييف VRF؛ أنظمة تدفئة تجارية وصناعية — سخانات، غلايات، ومكونات.",
    fabricationConstructionStructural: "التصنيع والإنشاء والهياكل",
    weldingConsumablesElectrodesWiresGases: "مستلزمات ومعدات لحام؛ مستلزمات قص وتشغيل المعادن؛ هياكل فولاذية — قنوات، عوارض، زوايا، ألواح.",
    fasteningAssembly: "التثبيت والتجميع",
    boltsScrewsNutsWashersStuds: "براغي، صواميل، حلقات، وأوتاد؛ مثبتات إنشائية — مسامير، مراسي، برشام.",
    filtrationFluidConditioning: "الترشيح وتكييف السوائل",
    hydraulicFiltersAirFiltersOil: "مرشحات هيدروليكية وهوائية وزيت ومصافي؛ مناولة المواد — سيور نقل، بكرات، ومكونات.",
    trustedManufacturers: "شركات مصنّعة موثوقة",
    brandsWeRepresent: "العلامات التجارية التي نمثلها",
    weSourceFromGloballyRecognized: "نقوم بالتوريد من شركات مصنّعة عالمية موثوقة لضمان موثوقية كل مشروع.",
    someOfOurClients: "بعض من عملائنا",
    whySourceFromUs: "لماذا تختار التوريد منا",
    ourSupplyPromise: "وعدنا في التوريد",
    productsSourcedFromGloballyCertified: "منتجات مصدرها شركات مصنّعة معتمدة عالميًا",
    deliveredWithFullDocumentationAnd: "تُسلَّم مع توثيق كامل واختبارات مطابقة",
    fastTurnaroundAndTechnicalSupport: "تسليم سريع ودعم فني",
    integrationReadyWithProjectEngineering: "جاهزة للتكامل مع خدمات الهندسة الخاصة بالمشروع",
    lookingForASpecificComponent: "تبحث عن مكوّن معيّن؟",
    sendUsYourBoqOr: "أرسل لنا جدول الكميات أو المواصفات وسنقوم بتوفيرها — بموثوقية وبالسعر المناسب.",
    requestAQuote: "اطلب عرض سعر",
    ourServices: "خدماتنا",
  },
  ku: {
    home: "سەرەکی",
    products: "بەرهەمەکانمان",
    productSupplySourcing: "دابینکردنی بەرهەم",
    aCompleteRangeOfElectrical: "کۆمەڵێکی تەواو لە بەرهەمی کارەبایی، ئامێری پێوانە و میکانیکی",
    weSupplyComponentsSystemsAnd: "پێکهاتە، سیستەم و ئامێری پێوانەی وردمان دابین دەکەین — لەگەڵ هاوبەشی لەگەڵ گەورەترین کۆمپانیا بەرهەمهێنەرە جیهانییەکان بۆ دڵنیابوون لە متمانەپێکراویی و وردی لە سەرچاوەی وزەوە تا خاڵی بەکارهێنان.",
    electrical: "کارەبایی",
    instrumentation: "ئامێری پێوانە",
    mechanical: "میکانیکی",
    productSupply: "دابینکردنی بەرهەم",
    electrical2: "کارەبایی",
    switchgearPanelComponents: "پێکهاتەی پانێڵی کلیلی کارەبایی",
    mccbMcbRcdContactorsOverload: "کلیلی MCCB، MCB، RCD، کۆنتاکتۆر، ڕیلەی پاراستن لە بارگرانی، مۆتۆر ستارتەر (ڕاستەوخۆ و ستار-دێلتا).",
    controlPanels: "پانێڵی کۆنترۆڵ",
    lvControlPanelsPlcPanels: "پانێڵی کۆنترۆڵی ڤۆڵتی نزم، پانێڵی PLC، پانێڵی MCC.",
    controlSignalingDevices: "ئامێری کۆنترۆڵ و نیشانە",
    pushButtonsSelectorSwitchesIndicator: "دوگمەی فشار، کلیلی هەڵبژاردن، لامپی نیشانەکەر، تایمەر، ڕیلەی چاودێریی فەیز.",
    backupCriticalPower: "وزەی یەدەگ و گرنگ",
    uninterruptiblePowerSuppliesUpsBattery: "دابینکەری وزەی بێ پچڕان (UPS)، بانکی باتری، ژێنەراتۆر.",
    powerConditioning: "ڕێکخستنی وزە",
    voltageRegulatorsRectifiersControlTransf: "ڕێکخەری ڤۆڵتاژ، ڕێکتیفایەر، ترانسفۆرمەری کۆنترۆڵ.",
    solarEnergySolutions: "چارەسەری وزەی خۆر",
    invertersChargeControllersSolarPanels: "ئینڤێرتەر، کۆنترۆڵەری شارژ، پانێڵی خۆر، و پێکهاتەی هاوسەنگیی سیستەم (BOS).",
    motors: "مۆتۆرەکان",
    acDcMotorsLvHv: "مۆتۆری AC و DC (ڤۆڵتی نزم و بەرز).",
    motorControlEfficiency: "کۆنترۆڵ و کارایی مۆتۆر",
    variableSpeedDrivesVsdSoft: "مۆتۆری خێرایی گۆڕاو (VSD)، سۆفت ستارتەر.",
    cables: "کێبڵەکان",
    powerCableLvMvHv: "کێبڵی وزە (ڤۆڵتی نزم، ناوەند، بەرز)، کێبڵی کۆنترۆڵ و پێوانە، کێبڵی داتا.",
    earthingGroundingSystems: "سیستەمی زەوی‌کردن",
    earthRodsEarthCableEarth: "میلەی زەوی‌کردن، کێبڵی زەوی‌کردن، میلەی پەیوەستکردن، گیرەکان، پێکهاتەی بێنتۆنایت.",
    cableManagement: "بەڕێوەبردنی کێبڵ",
    cableTraysLaddersConduitsAnd: "کەناڵی کێبڵ، پێپلیکانە، بۆری پاراستن، و سندوقی پەیوەستکردن.",
    heatTraceSystems: "سیستەمی گەرمکردنەوەی هاوپۆل",
    htPanelsHeatingCablesJunction: "پانێڵی HT، کێبڵی گەرمکردنەوە، سندوقی پەیوەستکردن، سێتی پەیوەستکردن، یەکەی کۆنترۆڵ، هەستیاری RTD.",
    lightingSolutions: "چارەسەری ڕووناکی",
    ledHidMetalHalideHigh: "ڕووناکی LED، HID، فلۆرێسێنت، ئامێری بەرگری لە تەقینەوە، ڕووناکی حاڵەتی نائاسایی، پڕۆژێکتەر.",
    powerEquipment: "ئامێری وزە",
    distributionTransformersProtectiveRelays: "ترانسفۆرمەری دابەشکردن، ڕیلەی پاراستن، کلیلی سیرکیت.",
    testMeasurement: "پشکنین و پێوانە",
    multimetersClampMetersInsulationTesters: "مەلتیمیتەر، کلامپ‌میتەر، پشکنەری ئیزۆلاسیۆن، شیکەرەوەی کوالیتیی وزە، ژمێرەری وزە، تۆمارکەری داتا، ئۆسیلۆسکۆپ.",
    productSupply2: "دابینکردنی بەرهەم",
    instrument: "ئامێری پێوانە",
    aCompleteRangeOfPrecision: "کۆمەڵێکی تەواو لە ئامێری پێوانەی وردمان بۆ پێوانە، کۆنترۆڵ و سەلامەتی، لەگەڵ هاوبەشی لەگەڵ گەورەترین کۆمپانیا بەرهەمهێنەرە جیهانییەکان بۆ دڵنیابوون لە متمانەپێکراویی و وردی.",
    temperature: "گەرمی",
    rtdsThermocouplesTemperatureTransmitters: "ئامێری RTD، جووتی گەرمایی، ترانسمیتەر و پێوەری پلەی گەرمی.",
    pressure: "فشار",
    pressureGaugesTransmittersTransducersSwi: "پێوەری فشار، ترانسمیتەر، ترانسدیوسەر، کلیل و نیشانەری دیجیتاڵ.",
    flow: "تێپەڕبوون",
    dpFlowMetersMagneticVortex: "پێوەری تێپەڕبوونی جیاوازیی فشار، میکناتیسی، ڤۆرتێکس، ئەڵتراسۆنیک، تۆربایین و کۆریۆلیس.",
    level: "ئاست",
    levelTransmittersRadarUltrasonicSwitches: "ترانسمیتەری ئاست (ڕادار، ئەڵتراسۆنیک)، کلیل، شووشەی بینین و نیشانەر.",
    gasProcessAnalysis: "شیکردنەوەی گاز و پرۆسە",
    oxygenInfraredIrLaserGas: "شیکەرەوەی ئۆکسجین، ئینفراسوور، شیکردنەوەی گاز بە لەیزەر، و هەستیاری pH/بەڕەسمیی.",
    controlValvesActuators: "ڤاڵڤ و ئاکتیوەیتەری کۆنترۆڵ",
    pneumaticAndElectricControlValves: "ڤاڵڤ و ئاکتیوەیتەری کۆنترۆڵی هەوایی و کارەبایی.",
    manifoldInstrumentValves: "ڤاڵڤی مانیفۆڵد و ئامێرەکان",
    manifoldValves235: "ڤاڵڤی مانیفۆڵد (2، 3، 5 ڤاڵڤ)، ڤاڵڤی دەرزی، ڤاڵڤی پشکنین، ڤاڵڤی گۆی.",
    fireGasDetectionFG: "دۆزینەوەی ئاگر و گاز",
    fireAlarmControlPanelsSmoke: "پانێڵی کۆنترۆڵی ئاگاداریی ئاگر، دۆزەرەوەی دووکەڵ، گەرمی و گاز، خاڵی بانگکردنی دەستی، ئامێری ئاگاداریی دەنگی و ڕووناکی.",
    processSafety: "سەلامەتیی پرۆسە",
    pressureSafetyValvesPsvSwitches: "ڤاڵڤی سەلامەتیی فشار (PSV)، کلیل، و پێکهاتەی ڕاگرتنی نائاسایی (ESD).",
    controlSystemComponents: "پێکهاتەی سیستەمی کۆنترۆڵ",
    processControllersSignalConditionersAnd: "یەکەی کۆنترۆڵی پرۆسە، ڕێکخەری نیشانە، و یەکەی چوونەژوورەوە/دەرچوونی PLC.",
    instrumentationCablingAccessories: "کێبڵ و پاشکۆی ئامێرەکان",
    instrumentationCablingJunctionBoxesAnd: "کێبڵی ئامێری پێوانە، سندوقی پەیوەستکردن، و بەربەستی سەلامەتیی بنەڕەتی.",
    productSupply3: "دابینکردنی بەرهەم",
    mechanical2: "میکانیکی",
    pipingValvesFittings: "بۆری، ڤاڵڤ و ئامێرەکان",
    pipesTubesFittingsFlangesElbows: "بۆری و ئامێر (فلانج، کوڵەکە، تی، ڕیدیوسەر، پەیوەندکەر)؛ ڤاڵڤی پیشەسازی (گەیت، گۆی، پشکنین، پەپوولە)؛ گاسکێت، هەڵقەی O، و سیلی میکانیکی.",
    powerTransmissionMotionControl: "گواستنەوەی هێز و کۆنترۆڵی جوڵە",
    ballRollerLinearBearingsFrom: "بێرینگی گۆیی، گۆڕوکی و هێڵی لە براندی پێشەنگ؛ کەمەری V، کەمەری کاتبەندی، زنجیر، گیر و کۆپلینگ.",
    rotatingEquipmentSupport: "ئامێری خولیو و پشتگیری",
    pumpsCompressorsFansBlowersTurbines: "پەمپ، کۆمپرێسەر، فان، بلۆوەر، تۆربایین، پارچە یەدەگی ڕەسەن، لوبریکانتی پیشەسازی و سیستەمی جوانکاریی ئۆتۆماتیکی.",
    hvacClimateControl: "هەواسازی و کۆنترۆڵی کەش",
    hvacAndVrfSystemComponents: "پێکهاتە و پارچە یەدەگی سیستەمی هەواسازی VRF؛ سیستەمی گەرمکردنەوەی بازرگانی و پیشەسازی — گەرمکەرەوە، بۆیلەر، و پێکهاتەکان.",
    fabricationConstructionStructural: "بەرهەمهێنان، دروستکردن و پێکهاتەکان",
    weldingConsumablesElectrodesWiresGases: "پێداویستی و ئامێری پەیوەستکردن؛ پێداویستی بڕین و کارکردن لەسەر کانزا؛ پێکهاتەی پۆڵایی — کەناڵ، تیر، گۆشە، لەوح.",
    fasteningAssembly: "چەسپاندن و کۆکردنەوە",
    boltsScrewsNutsWashersStuds: "بۆڵت، سۆمون، هەڵقە، و میخ؛ چەسپێنەری بیناسازی — چوی، لەنگەر، ڕیڤێت.",
    filtrationFluidConditioning: "پاڵاوتن و ڕێکخستنی شلەمەنی",
    hydraulicFiltersAirFiltersOil: "پاڵاوتنی هایدرۆلیکی، هەوایی و زەیت؛ گواستنەوەی ماددە — کەمەری گواستنەوە، پولی، و پێکهاتەکان.",
    trustedManufacturers: "کۆمپانیا بەرهەمهێنەرە متمانەپێکراوەکان",
    brandsWeRepresent: "براندە بازرگانییەکانی نوێنەرایەتیمان دەکەین",
    weSourceFromGloballyRecognized: "لە کۆمپانیا بەرهەمهێنەرە جیهانیی متمانەپێکراوەکان دابین دەکەین بۆ دڵنیابوون لە متمانەپێکراویی هەموو پڕۆژەیەک.",
    someOfOurClients: "هەندێک لە کڕیارەکانمان",
    whySourceFromUs: "بۆچی لە ئێمەوە دابین بکەیت",
    ourSupplyPromise: "بەڵێنی دابینکردنمان",
    productsSourcedFromGloballyCertified: "بەرهەمەکان لە کۆمپانیا بەرهەمهێنەرە پەسەندکراوە جیهانییەکانەوە دابین دەکرێن",
    deliveredWithFullDocumentationAnd: "لەگەڵ بەڵگەنامەی تەواو و تاقیکردنەوەی گونجاندن دەگەیەنرێن",
    fastTurnaroundAndTechnicalSupport: "گەیاندنی خێرا و پشتگیریی تەکنیکی",
    integrationReadyWithProjectEngineering: "ئامادەن بۆ تێکەڵبوون لەگەڵ خزمەتگوزاریی ئەندازیاریی پڕۆژە",
    lookingForASpecificComponent: "بەدوای پێکهاتەیەکی دیاریکراودا دەگەڕێیت؟",
    sendUsYourBoqOr: "خشتەی بڕوبا یان تایبەتمەندییەکانمان بۆ بنێرە و ئێمە دابینی دەکەین — بە متمانەپێکراوی و نرخێکی گونجاو.",
    requestAQuote: "داوای نرخنامە بکە",
    ourServices: "خزمەتگوزاریەکانمان",
  },
};
