// Every translated string on the projects page, one entry per key per language.
// The markup lives in projects.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    home: "Home",
    projects: "Our Project",
    n2025ModelProject: "2025 Model Project",
    engineeringElectrical50mwPvPower: "Engineering: Electrical — 50MW PV Power Plant",
    reliabilityAndImpactStudyFor: "Reliability and Impact Study for a 50MW PV Power Plant, delivered in coordination with Iraq’s Ministry of Electricity.",
    projectSnapshot: "Project Snapshot",
    reliabilityImpactStudyFor50mw: "Reliability & Impact Study for 50MW PV Power Plant",
    client: "Client",
    sinomaDccLine2Delta: "Sinoma DCC Line 2 — Delta Cement Company",
    type: "Type",
    n50mwDcSolarPowerPlant: "50MW (DC) Solar Power Plant Grid Connection Study",
    scope: "Scope",
    powerSystemAnalysisRegulatoryTechnical: "Power System Analysis, Regulatory Technical Support",
    location: "Location",
    bazyanSulaymaniyahIraq: "Bazyan, Sulaymaniyah, Iraq",
    inCoordinationWith: "In Coordination With",
    ministryOfElectricity: "Ministry of Electricity",
    status: "Status",
    scopeOfEngineeringServices: "Scope of Engineering Services",
    whatWeDelivered: "What We Delivered",
    powerSystemImpactStudyUsing: "Power System Impact Study using PSS®E, PSCAD and ETAP",
    protectionAndControlCoordinationReview: "Protection and Control Coordination Review",
    energyManagementSystemEmsEvaluation: "Energy Management System (EMS) Evaluation and Operation Procedure Arrangements",
    recommendationForTheVendorAnd: "Recommendation for the Vendor and the Client",
    technicalToolsExpertiseApplied: "Technical Tools & Expertise Applied",
    toolsSoftwareUsed: "Tools & Software Used",
    regulatoryTechnicalExecution: "Regulatory & Technical Execution",
    teamExpertiseInRegulatoryTechnical: "Team Expertise in Regulatory & Technical Execution",
    ourTeamBringsSpecializedKnowledge: "Our team brings specialized knowledge in delivering engineering studies in compliance with the Iraqi Grid Code and Ministry of Electricity (MoE) requirements.",
    detailedPowerSystemImpactStudies: "Detailed power system impact studies using PSS®E — harmonic distortion analysis, reactive power evaluation, and back-feed risk mitigation.",
    systemModelingSimulationAndScenario: "System modeling, simulation, and scenario-based technical recommendations.",
    evaluatingEmsPerformanceAndSettings: "Evaluating EMS performance and settings for efficient power flow control between the PV system and the grid.",
    protectionCoordinationReviewToAssess: "Protection Coordination Review to assess the PV system’s safety at the grid connection point.",
    technicalReportsAlignedWithMinistry: "Technical reports aligned with ministry expectations and local regulatory standards.",
    beyondThisProject: "Beyond This Project",
    everyProjectBackedByRoot: "Every Project Backed by Root-Cause Discipline",
    whicheverSystemWeDesignBuild: "Whichever system we design, build, or study, the same systematic troubleshooting methodology — FMEA, Fault Tree Analysis, and Ishikawa diagrams — protects reliability long after commissioning.",
    seeOurMethodology: "See Our Methodology",
    planningAPowerOrIndustrial: "Planning a Power or Industrial Project?",
    letSTalkAboutFeasibility: "Let’s talk about feasibility, grid studies, or full EPC-style delivery for your next project.",
    startAConversation: "Start a Conversation",
  },
  ar: {
    home: "الرئيسية",
    projects: "مشروعنا",
    n2025ModelProject: "مشروع نموذجي 2025",
    engineeringElectrical50mwPvPower: "الهندسة الكهربائية — محطة كهروضوئية بقدرة 50 ميغاواط",
    reliabilityAndImpactStudyFor: "دراسة الموثوقية والتأثير لمحطة طاقة كهروضوئية بقدرة 50 ميغاواط، نُفّذت بالتنسيق مع وزارة الكهرباء العراقية.",
    projectSnapshot: "لمحة عن المشروع",
    reliabilityImpactStudyFor50mw: "دراسة الموثوقية والتأثير لمحطة كهروضوئية 50 ميغاواط",
    client: "العميل",
    sinomaDccLine2Delta: "سينوما دي سي سي خط 2 — شركة دلتا للإسمنت",
    type: "النوع",
    n50mwDcSolarPowerPlant: "دراسة ربط شبكي لمحطة شمسية بقدرة 50 ميغاواط (تيار مستمر)",
    scope: "النطاق",
    powerSystemAnalysisRegulatoryTechnical: "تحليل النظام الكهربائي ودعم فني تنظيمي",
    location: "الموقع",
    bazyanSulaymaniyahIraq: "بازيان، السليمانية، العراق",
    inCoordinationWith: "بالتنسيق مع",
    ministryOfElectricity: "وزارة الكهرباء",
    status: "الحالة",
    scopeOfEngineeringServices: "نطاق الخدمات الهندسية",
    whatWeDelivered: "ما الذي نفّذناه",
    powerSystemImpactStudyUsing: "دراسة تأثير النظام الكهربائي باستخدام PSS®E وPSCAD وETAP",
    protectionAndControlCoordinationReview: "مراجعة تنسيق الحماية والتحكم",
    energyManagementSystemEmsEvaluation: "تقييم نظام إدارة الطاقة (EMS) وترتيب إجراءات التشغيل",
    recommendationForTheVendorAnd: "تقديم توصيات للمورّد والعميل",
    technicalToolsExpertiseApplied: "الأدوات والخبرات الفنية المطبّقة",
    toolsSoftwareUsed: "الأدوات والبرمجيات المستخدمة",
    regulatoryTechnicalExecution: "التنفيذ الفني والتنظيمي",
    teamExpertiseInRegulatoryTechnical: "خبرة الفريق في التنفيذ الفني والتنظيمي",
    ourTeamBringsSpecializedKnowledge: "يمتلك فريقنا معرفة متخصصة في تنفيذ الدراسات الهندسية بما يتوافق مع كود الشبكة العراقي ومتطلبات وزارة الكهرباء.",
    detailedPowerSystemImpactStudies: "دراسات تأثير مفصّلة للنظام الكهربائي باستخدام PSS®E — تحليل التشوه التوافقي، تقييم القدرة الردية، والتخفيف من مخاطر التغذية العكسية.",
    systemModelingSimulationAndScenario: "نمذجة النظام والمحاكاة وتوصيات فنية قائمة على السيناريوهات.",
    evaluatingEmsPerformanceAndSettings: "تقييم أداء وإعدادات نظام إدارة الطاقة لضمان تحكم فعّال بسريان الطاقة بين النظام الشمسي والشبكة.",
    protectionCoordinationReviewToAssess: "مراجعة تنسيق الحماية لتقييم سلامة النظام الشمسي عند نقطة الربط بالشبكة.",
    technicalReportsAlignedWithMinistry: "تقارير فنية متوافقة مع متطلبات الوزارة والمعايير التنظيمية المحلية.",
    beyondThisProject: "إضافة إلى هذا المشروع",
    everyProjectBackedByRoot: "كل مشروع مدعوم بمنهجية تحليل الأسباب الجذرية",
    whicheverSystemWeDesignBuild: "أيًا كان النظام الذي نصممه أو ننفّذه أو ندرسه، فإن المنهجية المنظمة نفسها لاستكشاف الأعطال — FMEA وتحليل شجرة الأعطال ومخططات إيشيكاوا — تحمي الموثوقية لفترة طويلة بعد التشغيل.",
    seeOurMethodology: "اطّلع على منهجيتنا",
    planningAPowerOrIndustrial: "تخطط لمشروع طاقة أو صناعي؟",
    letSTalkAboutFeasibility: "لنتحدث عن دراسات الجدوى أو دراسات الشبكة أو التنفيذ الكامل لمشروعك القادم.",
    startAConversation: "ابدأ محادثة",
  },
  ku: {
    home: "سەرەکی",
    projects: "پڕۆژەکەمان",
    n2025ModelProject: "پڕۆژەی نموونەیی 2025",
    engineeringElectrical50mwPvPower: "ئەندازیاری کارەبایی — وێستگەی خۆرەکی بە توانای 50 مێگاوات",
    reliabilityAndImpactStudyFor: "خوێندنەوەی متمانەپێکراوی و کاریگەری بۆ وێستگەی وزەی خۆرەکی بە توانای 50 مێگاوات، بە هاوکاریی لەگەڵ وەزارەتی کارەبای عێراق جێبەجێ کراوە.",
    projectSnapshot: "پوختەیەک لەسەر پڕۆژە",
    reliabilityImpactStudyFor50mw: "خوێندنەوەی متمانەپێکراوی و کاریگەری بۆ وێستگەی خۆرەکی 50 مێگاوات",
    client: "کڕیار",
    sinomaDccLine2Delta: "سینۆما دی سی سی هێڵی 2 — کۆمپانیای دێلتا سیمێنت",
    type: "جۆر",
    n50mwDcSolarPowerPlant: "خوێندنەوەی پەیوەستکردنی گرید بۆ وێستگەی خۆر بە توانای 50 مێگاوات (DC)",
    scope: "مەودا",
    powerSystemAnalysisRegulatoryTechnical: "شیکردنەوەی سیستەمی کارەبایی و پشتگیری تەکنیکی ڕێکخراوەیی",
    location: "شوێن",
    bazyanSulaymaniyahIraq: "بازیان، سلێمانی، عێراق",
    inCoordinationWith: "بە هاوکاریی لەگەڵ",
    ministryOfElectricity: "وەزارەتی کارەبا",
    status: "دۆخ",
    scopeOfEngineeringServices: "مەودای خزمەتگوزاریی ئەندازیاری",
    whatWeDelivered: "چیمان جێبەجێ کرد",
    powerSystemImpactStudyUsing: "خوێندنەوەی کاریگەری سیستەمی کارەبایی بە بەکارهێنانی PSS®E و PSCAD و ETAP",
    protectionAndControlCoordinationReview: "پێداچوونەوەی ڕێکخستنی پاراستن و کۆنترۆڵ",
    energyManagementSystemEmsEvaluation: "هەڵسەنگاندنی سیستەمی بەڕێوەبردنی وزە (EMS) و ڕێکخستنی هەنگاوەکانی کارپێکردن",
    recommendationForTheVendorAnd: "پێشکەشکردنی ڕاسپاردە بۆ دابینکەر و کڕیار",
    technicalToolsExpertiseApplied: "ئامراز و شارەزاییە تەکنیکییە بەکارهاتووەکان",
    toolsSoftwareUsed: "ئامراز و نەرمەکالای بەکارهاتوو",
    regulatoryTechnicalExecution: "جێبەجێکردنی تەکنیکی و ڕێکخراوەیی",
    teamExpertiseInRegulatoryTechnical: "شارەزاییی تیم لە جێبەجێکردنی تەکنیکی و ڕێکخراوەیی",
    ourTeamBringsSpecializedKnowledge: "تیمەکەمان زانیاریی پسپۆڕانەی هەیە لە جێبەجێکردنی خوێندنەوە ئەندازیارییەکان بەگوێرەی کۆدی گریدی عێراق و پێداویستیەکانی وەزارەتی کارەبا.",
    detailedPowerSystemImpactStudies: "خوێندنەوەی کاریگەری وردی سیستەمی کارەبایی بە بەکارهێنانی PSS®E — شیکردنەوەی خەوشی هارمۆنیک، هەڵسەنگاندنی هێزی ڕیئاکتیڤ، و کەمکردنەوەی مەترسیی گەڕانەوەی تێچووەوە.",
    systemModelingSimulationAndScenario: "مۆدێلکردنی سیستەم، شێوەیی، و ڕاسپاردەی تەکنیکی بەرەو سیناریۆکان.",
    evaluatingEmsPerformanceAndSettings: "هەڵسەنگاندنی ئەدایەن و ڕێکخستنەکانی سیستەمی بەڕێوەبردنی وزە بۆ دڵنیابوون لە کۆنترۆڵێکی کاریگەر بەسەر سریانی وزەدا لەنێوان سیستەمی خۆرەکی و گرید.",
    protectionCoordinationReviewToAssess: "پێداچوونەوەی ڕێکخستنی پاراستن بۆ هەڵسەنگاندنی سەلامەتیی سیستەمی خۆرەکی لە خاڵی پەیوەستبوون بە گریدەوە.",
    technicalReportsAlignedWithMinistry: "ڕاپۆرتی تەکنیکی گونجاو لەگەڵ پێداویستیەکانی وەزارەت و ستانداردە ڕێکخراوەییە ناوخۆییەکان.",
    beyondThisProject: "سەرباری ئەم پڕۆژەیە",
    everyProjectBackedByRoot: "هەموو پڕۆژەیەک بە ڕێبازی شیکردنەوەی هۆکاری بنەڕەتی پشتگیری کراوە",
    whicheverSystemWeDesignBuild: "هەرچی سیستەمێک دیزاینی دەکەین، جێبەجێی دەکەین یان دەیخوێنینەوە، هەمان ڕێبازی ڕێکخراوی شیکردنەوەی کێشە — FMEA و شیکردنەوەی دارەی کێشەکان و پلانی ئیشیکاوا — متمانەپێکراویی بۆ ماوەیەکی درێژ دوای کارپێکردن دەپارێزێت.",
    seeOurMethodology: "ڕێبازمان ببینە",
    planningAPowerOrIndustrial: "پلان بۆ پڕۆژەیەکی وزە یان پیشەسازی دادەڕێژیت؟",
    letSTalkAboutFeasibility: "با باسی خوێندنەوەی گونجاوی، خوێندنەوەی گرید، یان جێبەجێکردنی تەواوی پڕۆژەی داهاتووت بکەین.",
    startAConversation: "گفتوگۆیەک دەست پێبکە",
  },
};
