// Every translated string on the services page, one entry per key per language.
// The markup lives in services.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    home: "Home",
    services: "Services",
    whatWeOffer: "What We Offer",
    engineeringConstructionSupplyUnderOne: "Engineering, Construction & Supply Under One Roof",
    deliveringSpecializedEngineeringServices: "Delivering specialized engineering services alongside reliable supply of electrical, mechanical, and instrumentation systems — from first sketch to full operation.",
    whatWeDo: "What We Do",
    fiveServicePillars: "Five Service Pillars",
    designEngineering: "Design & Engineering",
    constructionInstallation: "Construction & Installation",
    systemCommissioningStartUp: "System Commissioning & Start-Up",
    productSupplySourcing: "Product Supply & Sourcing",
    operationsSupportTroubleshooting: "Operations Support & Troubleshooting",
    ourEngineeringServicesInclude: "Our Engineering Services Include",
    fiveEngineeringDisciplines: "Five Engineering Disciplines",
    feasibilityStudies: "Feasibility & Studies",
    technicalAndEconomicFeasibilityStudies: "Technical and economic feasibility studies",
    conceptualDesignAndProjectScoping: "Conceptual design and project scoping",
    siteSurveysAndDataCollection: "Site surveys and data collection",
    electricalEngineering: "Electrical Engineering",
    detailedElectricalDesignLvMv: "Detailed electrical design (LV, MV, HV systems)",
    powerManagementSystems: "Power management systems",
    protectionCoordinationStudies: "Protection coordination studies",
    loadFlowShortCircuitStability: "Load flow, short circuit & stability studies",
    harmonicAnalysisAndPowerQuality: "Harmonic analysis and power quality studies",
    powerSystemSimulationEtapPscad: "Power system simulation (ETAP, PSCAD, PSS/E)",
    scadaAndAutomationIntegration: "SCADA and automation integration",
    mechanicalEngineering: "Mechanical Engineering",
    cableTrayAndCableLadder: "Cable tray and cable ladder installation",
    hvacSystemsDuctsDampersVrf: "HVAC systems (ducts, dampers, VRF, accessories)",
    tankPipingPaintingInspection: "Tank, piping & painting inspection",
    pipeInstallationWelding: "Pipe installation & welding",
    nonDestructiveTestingPtRt: "Non-Destructive Testing — PT, RT, UT, MT",
    rotatingEquipmentInstallation: "Rotating equipment installation",
    fireFightingSystemsPumpsSprinklers: "Fire-fighting systems (pumps, sprinklers, FM200, hydrants)",
    lubeOilFiltrationTreatment: "Lube oil filtration & treatment",
    structuralSteelInstallation: "Structural steel installation",
    instrumentationEngineering: "Instrumentation Engineering",
    fieldInstrumentSpecificationSizingPressu: "Field instrument specification & sizing (pressure, temperature, flow, level)",
    controlLoopDesignAndInstrument: "Control loop design and instrument index/data sheets",
    hookUpDrawingsAndInstrument: "Hook-up drawings and instrument cabling design",
    junctionBoxMarshallingCabinetLayout: "Junction box & marshalling cabinet layout",
    fireGasFGDetection: "Fire & gas (F&G) detection system design",
    automationControl: "Automation & Control",
    dcsPlcScadaArchitectureDesign: "DCS / PLC / SCADA architecture design",
    controlPhilosophyAndLogicDevelopment: "Control philosophy and logic development",
    hmiDesignAndOperatorInterface: "HMI design and operator interface layout",
    analyzerSystemIntegrationGasLiquid: "Analyzer system integration (gas & liquid)",
    dcsPlcPanelWiringAnd: "DCS/PLC panel wiring and I/O architecture",
    preCommissioningCalibrationCommissioning: "Pre-commissioning, calibration & commissioning support",
    fieldExecution: "Field Execution",
    constructionCapability: "Construction Capability",
    aSingleFieldTeamExecuting: "A single field team executing electrical, mechanical, and instrumentation scopes together.",
    operationsSupport: "Operations Support",
    advancedTechnicalTroubleshootingRootCaus: "Advanced Technical Troubleshooting & Root Cause Analysis",
    aSystematicDataDrivenApproach: "A systematic, data-driven approach to rapidly identify the root cause of complex issues in electrical, mechanical, and instrumentation systems — minimizing downtime and preventing recurrence.",
    problemDefinitionDataCollection: "Problem Definition & Data Collection",
    thoroughReviewOfSystemDocumentation: "Thorough review of system documentation, including P&ID and electrical schematic diagrams.",
    structuredAnalysisRootCauseId: "Structured Analysis & Root Cause ID",
    fmeaFaultTreeAnalysisFta: "FMEA, Fault Tree Analysis (FTA), and Cause-and-Effect (Ishikawa) diagrams to explore every potential cause.",
    solutionImplementationValidation: "Solution Implementation & Validation",
    weDevelopAndExecuteA: "We develop and execute a corrective action plan, verifying the fix restores system reliability and performance.",
    haveAScopeInMind: "Have a Scope in Mind?",
    sendUsYourRequirementsAnd: "Send us your requirements and our engineering team will get back to you with a tailored proposal.",
    requestAQuote: "Request a Quote",
    browseProducts: "Browse Products",
  },
  ar: {
    home: "الرئيسية",
    services: "خدماتنا",
    whatWeOffer: "ما نقدّمه",
    engineeringConstructionSupplyUnderOne: "هندسة وتنفيذ وتوريد تحت سقف واحد",
    deliveringSpecializedEngineeringServices: "نقدّم خدمات هندسية متخصصة إلى جانب توريد موثوق لأنظمة كهربائية وميكانيكية وأجهزة قياس — من أول رسم إلى التشغيل الكامل.",
    whatWeDo: "ماذا نقدّم",
    fiveServicePillars: "خمسة محاور خدمية",
    designEngineering: "التصميم والهندسة",
    constructionInstallation: "التنفيذ والتركيب",
    systemCommissioningStartUp: "التشغيل التجريبي والانطلاق",
    productSupplySourcing: "توريد المنتجات",
    operationsSupportTroubleshooting: "دعم التشغيل واستكشاف الأعطال",
    ourEngineeringServicesInclude: "تشمل خدماتنا الهندسية",
    fiveEngineeringDisciplines: "خمسة تخصصات هندسية",
    feasibilityStudies: "دراسات الجدوى",
    technicalAndEconomicFeasibilityStudies: "دراسات جدوى فنية واقتصادية",
    conceptualDesignAndProjectScoping: "تصميم مفاهيمي وتحديد نطاق المشروع",
    siteSurveysAndDataCollection: "مسوحات ميدانية وجمع البيانات",
    electricalEngineering: "الهندسة الكهربائية",
    detailedElectricalDesignLvMv: "تصميم كهربائي تفصيلي (أنظمة منخفضة ومتوسطة وعالية الجهد)",
    powerManagementSystems: "أنظمة إدارة الطاقة",
    protectionCoordinationStudies: "دراسات تنسيق الحماية",
    loadFlowShortCircuitStability: "دراسات سريان الحمل والدائرة القصيرة والاستقرار",
    harmonicAnalysisAndPowerQuality: "تحليل التوافقيات ودراسات جودة الطاقة",
    powerSystemSimulationEtapPscad: "محاكاة أنظمة الطاقة (ETAP, PSCAD, PSS/E)",
    scadaAndAutomationIntegration: "تكامل أنظمة SCADA والأتمتة",
    mechanicalEngineering: "الهندسة الميكانيكية",
    cableTrayAndCableLadder: "تركيب مجاري وسلالم الكابلات",
    hvacSystemsDuctsDampersVrf: "أنظمة التكييف (المجاري، الدمبرات، VRF، الملحقات)",
    tankPipingPaintingInspection: "فحص الخزانات والأنابيب والطلاء",
    pipeInstallationWelding: "تركيب ولحام الأنابيب",
    nonDestructiveTestingPtRt: "الفحص غير الإتلافي — PT, RT, UT, MT",
    rotatingEquipmentInstallation: "تركيب المعدات الدوّارة",
    fireFightingSystemsPumpsSprinklers: "أنظمة الإطفاء (مضخات، رشاشات، FM200، صنابير حريق)",
    lubeOilFiltrationTreatment: "ترشيح ومعالجة زيوت التشحيم",
    structuralSteelInstallation: "تركيب الهياكل الفولاذية",
    instrumentationEngineering: "هندسة أجهزة القياس",
    fieldInstrumentSpecificationSizingPressu: "تحديد ومعايرة أجهزة القياس الميدانية (ضغط، حرارة، تدفق، مستوى)",
    controlLoopDesignAndInstrument: "تصميم حلقات التحكم وفهارس/بطاقات بيانات الأجهزة",
    hookUpDrawingsAndInstrument: "مخططات الربط وتصميم كابلات الأجهزة",
    junctionBoxMarshallingCabinetLayout: "تخطيط صناديق التوصيل وخزائن التجميع",
    fireGasFGDetection: "تصميم أنظمة كشف الحريق والغاز",
    automationControl: "الأتمتة والتحكم",
    dcsPlcScadaArchitectureDesign: "تصميم بنية أنظمة DCS / PLC / SCADA",
    controlPhilosophyAndLogicDevelopment: "تطوير فلسفة ومنطق التحكم",
    hmiDesignAndOperatorInterface: "تصميم واجهات التشغيل HMI",
    analyzerSystemIntegrationGasLiquid: "دمج أنظمة التحليل (غاز وسائل)",
    dcsPlcPanelWiringAnd: "توصيل لوحات DCS/PLC وبنية المداخل والمخارج",
    preCommissioningCalibrationCommissioning: "دعم ما قبل التشغيل والمعايرة والتشغيل التجريبي",
    fieldExecution: "التنفيذ الميداني",
    constructionCapability: "قدرات التنفيذ",
    aSingleFieldTeamExecuting: "فريق ميداني واحد ينفّذ الأعمال الكهربائية والميكانيكية وأجهزة القياس معًا.",
    operationsSupport: "دعم التشغيل",
    advancedTechnicalTroubleshootingRootCaus: "استكشاف الأعطال المتقدم وتحليل الأسباب الجذرية",
    aSystematicDataDrivenApproach: "نهج منهجي قائم على البيانات لتحديد الأسباب الجذرية للمشكلات المعقّدة بسرعة في الأنظمة الكهربائية والميكانيكية وأجهزة القياس — لتقليل التوقف ومنع تكرار الأعطال.",
    problemDefinitionDataCollection: "تحديد المشكلة وجمع البيانات",
    thoroughReviewOfSystemDocumentation: "مراجعة شاملة لوثائق النظام، بما في ذلك مخططات P&ID والمخططات الكهربائية.",
    structuredAnalysisRootCauseId: "تحليل منظم وتحديد السبب الجذري",
    fmeaFaultTreeAnalysisFta: "تحليل FMEA وشجرة الأعطال FTA ومخططات إيشيكاوا لاستكشاف كل الأسباب المحتملة.",
    solutionImplementationValidation: "تنفيذ الحل والتحقق منه",
    weDevelopAndExecuteA: "نُطوّر وننفّذ خطة إجراء تصحيحي، مع التحقق من استعادة موثوقية النظام وأدائه.",
    haveAScopeInMind: "لديك نطاق عمل محدد؟",
    sendUsYourRequirementsAnd: "أرسل لنا متطلباتك وسيقوم فريقنا الهندسي بالرد عليك بعرض مخصص.",
    requestAQuote: "اطلب عرض سعر",
    browseProducts: "تصفح المنتجات",
  },
  ku: {
    home: "سەرەکی",
    services: "خزمەتگوزاریەکانمان",
    whatWeOffer: "چی پێشکەش دەکەین",
    engineeringConstructionSupplyUnderOne: "ئەندازیاری، جێبەجێکردن و دابینکردن لەژێر یەک سەقفدا",
    deliveringSpecializedEngineeringServices: "خزمەتگوزاری ئەندازیاری پسپۆڕانە پێشکەش دەکەین لەگەڵ دابینکردنی متمانەپێکراوی سیستەمی کارەبایی، میکانیکی و ئامێری پێوانە — لە یەکەم وێنە تا کارپێکردنی تەواو.",
    whatWeDo: "چیمان پێشکەشە",
    fiveServicePillars: "پێنج بواری خزمەتگوزاری",
    designEngineering: "دیزاین و ئەندازیاری",
    constructionInstallation: "جێبەجێکردن و دامەزراندن",
    systemCommissioningStartUp: "کارپێکردنی تاقیکارییانە و دەستپێکردن",
    productSupplySourcing: "دابینکردنی بەرهەم",
    operationsSupportTroubleshooting: "پشتگیری کارپێکردن و شیکردنەوەی کێشە",
    ourEngineeringServicesInclude: "خزمەتگوزاریە ئەندازیاریەکانمان لەخۆدەگرێت",
    fiveEngineeringDisciplines: "پێنج پسپۆڕیی ئەندازیاری",
    feasibilityStudies: "خوێندنەوەی گونجاوی",
    technicalAndEconomicFeasibilityStudies: "خوێندنەوەی گونجاوی تەکنیکی و ئابووری",
    conceptualDesignAndProjectScoping: "دیزاینی چەمکی و دیاریکردنی مەودای پڕۆژە",
    siteSurveysAndDataCollection: "پێداچوونەوەی مەیدانی و کۆکردنەوەی داتا",
    electricalEngineering: "ئەندازیاری کارەبایی",
    detailedElectricalDesignLvMv: "دیزاینی کارەبایی وردی (سیستەمی ڤۆڵتی نزم، ناوەند و بەرز)",
    powerManagementSystems: "سیستەمی بەڕێوەبردنی وزە",
    protectionCoordinationStudies: "خوێندنەوەی ڕێکخستنی پاراستن",
    loadFlowShortCircuitStability: "خوێندنەوەی سریانی بار، سیرکیتی کورت و جێگیری",
    harmonicAnalysisAndPowerQuality: "شیکردنەوەی هارمۆنیک و خوێندنەوەی کوالیتیی وزە",
    powerSystemSimulationEtapPscad: "شێوەیی سیستەمی وزە (ETAP, PSCAD, PSS/E)",
    scadaAndAutomationIntegration: "تەواوکردنی سیستەمی SCADA و ئۆتۆماسیۆن",
    mechanicalEngineering: "ئەندازیاری میکانیکی",
    cableTrayAndCableLadder: "دامەزراندنی کەناڵ و پێپلیکانەی کێبڵ",
    hvacSystemsDuctsDampersVrf: "سیستەمی هەواسازی (کەناڵ، دامپەر، VRF، پاشکۆکان)",
    tankPipingPaintingInspection: "پشکنینی مەخزەن، بۆری و بۆیاخ",
    pipeInstallationWelding: "دامەزراندن و پەیوەستکردنی بۆری",
    nonDestructiveTestingPtRt: "پشکنینی نا وێرانکەر — PT, RT, UT, MT",
    rotatingEquipmentInstallation: "دامەزراندنی ئامێری خولیو",
    fireFightingSystemsPumpsSprinklers: "سیستەمی کوژاندنەوەی ئاگر (پەمپ، سپرینکلەر، FM200، حەنەفیەی ئاگرکوژاندنەوە)",
    lubeOilFiltrationTreatment: "پاڵاوتن و چارەسەرکردنی زەیتی جوانکاری",
    structuralSteelInstallation: "دامەزراندنی پێکهاتەی پۆڵایی",
    instrumentationEngineering: "ئەندازیاری ئامێری پێوانە",
    fieldInstrumentSpecificationSizingPressu: "دیاریکردن و پێوانەکردنی ئامێری پێوانەی مەیدانی (فشار، پلەی گەرمی، تێپەڕبوون، ئاست)",
    controlLoopDesignAndInstrument: "دیزاینی حەڵقەی کۆنترۆڵ و ئیندێکس/کارتی زانیاریی ئامێرەکان",
    hookUpDrawingsAndInstrument: "پلانی پەیوەستکردن و دیزاینی کێبڵی ئامێرەکان",
    junctionBoxMarshallingCabinetLayout: "پلاندانانی سندوقی پەیوەستکردن و دۆلابی کۆکردنەوە",
    fireGasFGDetection: "دیزاینی سیستەمی دۆزینەوەی ئاگر و گاز",
    automationControl: "ئۆتۆماسیۆن و کۆنترۆڵ",
    dcsPlcScadaArchitectureDesign: "دیزاینی پێکهاتەی سیستەمی DCS / PLC / SCADA",
    controlPhilosophyAndLogicDevelopment: "پەرەپێدانی فەلسەفە و لۆجیکی کۆنترۆڵ",
    hmiDesignAndOperatorInterface: "دیزاینی ڕووکاری کارپێکردن HMI",
    analyzerSystemIntegrationGasLiquid: "تێکەڵکردنی سیستەمی شیکردنەوە (گاز و شلەیی)",
    dcsPlcPanelWiringAnd: "پەیوەستکردنی پانێڵی DCS/PLC و پێکهاتەی چوونەژوورەوە/دەرچوون",
    preCommissioningCalibrationCommissioning: "پشتگیری پێش کارپێکردن، پێوانەکردن و کارپێکردنی تاقیکارییانە",
    fieldExecution: "جێبەجێکردنی مەیدانی",
    constructionCapability: "توانای جێبەجێکردن",
    aSingleFieldTeamExecuting: "یەک تیمی مەیدانی کاری کارەبایی، میکانیکی و ئامێری پێوانە پێکەوە جێبەجێ دەکات.",
    operationsSupport: "پشتگیری کارپێکردن",
    advancedTechnicalTroubleshootingRootCaus: "شیکردنەوەی پێشکەوتووی کێشە و شیکردنەوەی هۆکاری بنەڕەتی",
    aSystematicDataDrivenApproach: "ڕێبازێکی سیستەماتیکی بەرەو داتا بۆ دیاریکردنی خێرای هۆکاری بنەڕەتی کێشە ئاڵۆزەکان لە سیستەمی کارەبایی، میکانیکی و ئامێری پێوانەدا — بۆ کەمکردنەوەی وەستان و ڕێگریکردن لە دووبارەبوونەوەی کێشەکان.",
    problemDefinitionDataCollection: "دیاریکردنی کێشە و کۆکردنەوەی داتا",
    thoroughReviewOfSystemDocumentation: "پێداچوونەوەیەکی گشتگیر بۆ بەڵگەنامەکانی سیستەم، لەوانە پلانی P&ID و پلانی کارەبایی.",
    structuredAnalysisRootCauseId: "شیکردنەوەیەکی ڕێکخراو و دیاریکردنی هۆکاری بنەڕەتی",
    fmeaFaultTreeAnalysisFta: "شیکردنەوەی FMEA، دارەی کێشەکان FTA و پلانی ئیشیکاوا بۆ گەڕان بەدوای هەموو هۆکارە ئەگەرییەکاندا.",
    solutionImplementationValidation: "جێبەجێکردنی چارەسەر و دڵنیابوونەوە لێی",
    weDevelopAndExecuteA: "پلانی چارەسەرکردنی هەڵە پەرەپێدەدەین و جێبەجێی دەکەین، لەگەڵ دڵنیابوونەوە لە گەڕانەوەی متمانەپێکراویی و ئەدایەنی سیستەم.",
    haveAScopeInMind: "مەودای کاری دیاریکراوت هەیە؟",
    sendUsYourRequirementsAnd: "پێداویستیەکانت بۆمان بنێرە و تیمی ئەندازیاریمان بە پێشنیارێکی تایبەت وەڵامت دەداتەوە.",
    requestAQuote: "داوای نرخنامە بکە",
    browseProducts: "بەرهەمەکان ببینە",
  },
};
