// Every translated string on the services page, one entry per key per language.
// The markup lives in services.jsx and is shared by all three, so a layout
// change is made once instead of being copied into three files that nothing
// keeps in step.
//
// Routes are deliberately NOT here — they are derived from `lang` via
// pagePath(), so a URL change cannot leave one language on a stale path.
export const STRINGS = {
  en: {
    home: "Home",
    services: "Services",
    whatWeOffer: "What We Offer",
    engineeringConstructionSupplyUnderOne: "Engineering, Construction & Supply Under One Roof",
    deliveringSpecializedEngineeringServices: "Delivering specialized engineering services alongside reliable supply of electrical, mechanical, and instrumentation systems, from first sketch to full operation.",
    whatWeDo: "What We Do",
    sixServicePillars: "Six Service Pillars",
    designEngineering: "Design & Engineering",
    designEngineeringPillarDesc: "Feasibility studies, conceptual design, and detailed electrical, mechanical & instrumentation engineering.",
    constructionInstallation: "Construction & Installation",
    constructionInstallationPillarDesc: "Full field execution across electrical, mechanical, and instrumentation systems, built to spec.",
    systemCommissioningStartUp: "System Commissioning & Start-Up",
    systemCommissioningPillarDesc: "Structured pre-commissioning, testing, and start-up support for a smooth handover.",
    productSupplySourcing: "Product Supply & Sourcing",
    productSupplyPillarDesc: "Electrical, instrumentation & mechanical components sourced from trusted global manufacturers.",
    operationsSupportTroubleshooting: "Operations Support/Troubleshooting and RCA",
    operationsSupportPillarDesc: "Root-cause analysis and rapid response that minimizes downtime and protects reliability.",
    contractingServices: "Contracting Services",
    contractingServicesPillarDesc: "Full-scope EPC contracting, from site preparation and procurement to final handover, as prime or specialized subcontractor.",
    ourEngineeringServicesInclude: "Our Engineering Services Include",
    fiveEngineeringDisciplines: "Five Engineering Disciplines",
    feasibilityStudies: "Feasibility & Studies",
    technicalAndEconomicFeasibilityStudies: "Technical and economic feasibility studies",
    conceptualDesignAndProjectScoping: "Conceptual design and project scoping",
    siteSurveysAndDataCollection: "Site surveys and data collection",
    electricalEngineering: "Electrical Engineering",
    detailedElectricalDesignLvMv: "Detailed electrical design (LV, MV, HV systems)",
    powerManagementSystems: "Power management systems",
    protectionCoordinationStudies: "Protection coordination studies",
    loadFlowShortCircuitStability: "Load flow, short circuit & stability studies",
    harmonicAnalysisAndPowerQuality: "Harmonic analysis and power quality studies",
    powerSystemSimulationEtapPscad: "Power system simulation (ETAP, PSCAD, PSS/E)",
    scadaAndAutomationIntegration: "SCADA and automation integration",
    mechanicalEngineering: "Mechanical Engineering",
    cableTrayAndCableLadder: "Cable tray and cable ladder installation",
    hvacSystemsDuctsDampersVrf: "HVAC systems (ducts, dampers, VRF, accessories)",
    tankPipingPaintingInspection: "Tank, piping & painting inspection",
    pipeInstallationWelding: "Pipe installation & welding",
    nonDestructiveTestingPtRt: "Non-Destructive Testing: PT, RT, UT, MT",
    rotatingEquipmentInstallation: "Rotating equipment installation",
    fireFightingSystemsPumpsSprinklers: "Fire-fighting systems (pumps, sprinklers, FM200, hydrants)",
    lubeOilFiltrationTreatment: "Lube oil filtration & treatment",
    structuralSteelInstallation: "Structural steel installation",
    instrumentationEngineering: "Instrumentation Engineering",
    fieldInstrumentSpecificationSizingPressu: "Field instrument specification & sizing (pressure, temperature, flow, level)",
    controlLoopDesignAndInstrument: "Control loop design and instrument index/data sheets",
    hookUpDrawingsAndInstrument: "Hook-up drawings and instrument cabling design",
    junctionBoxMarshallingCabinetLayout: "Junction box & marshalling cabinet layout",
    fireGasFGDetection: "Fire & gas (F&G) detection system design",
    automationControl: "Automation & Control",
    dcsPlcScadaArchitectureDesign: "DCS / PLC / SCADA architecture design",
    controlPhilosophyAndLogicDevelopment: "Control philosophy and logic development",
    hmiDesignAndOperatorInterface: "HMI design and operator interface layout",
    analyzerSystemIntegrationGasLiquid: "Analyzer system integration (gas & liquid)",
    dcsPlcPanelWiringAnd: "DCS/PLC panel wiring and I/O architecture",
    preCommissioningCalibrationCommissioning: "Pre-commissioning, calibration & commissioning support",
    fieldExecution: "Field Execution",
    constructionCapability: "Construction Capability",
    aSingleFieldTeamExecuting: "A single field team executing electrical, mechanical, and instrumentation scopes together.",
    contractingEyebrow: "Contracting Services",
    comprehensiveEpcContracting: "Comprehensive Engineering, Procurement, and Construction (EPC) Contracting",
    brightVolitionProvidesEndToEnd: "Bright Volition provides end-to-end Contracting Services for industrial, energy, and infrastructure projects across the Kurdistan Region and greater Iraq. As a registered Iraqi company located in Kurdistan of Iraq, we combine our specialized engineering expertise with robust project management to deliver full-scale execution, handling everything from initial site preparation to final handover.",
    whetherActingAsAPrime: "Whether acting as a prime contractor or a specialized subcontractor, we ensure your project is completed safely, on schedule, and in strict compliance with local regulations and international standards.",
    coreCapabilities: "Core Capabilities",
    electroMechanicalContracting: "Electro-Mechanical Contracting. Full E&I installation, equipment positioning, and integration for power plants and industrial facilities.",
    procurementLogistics: "Procurement & Logistics. Global sourcing, customs clearance, and delivery of high-spec engineering components.",
    projectManagementBullet: "Project Management. Complete PMO oversight (HSE, quality control) and liaison with power authorities.",
    whyBrightVolitionContracting: "Why Bright Volition",
    singlePointAccountability: "Single-Point Accountability. Unified design, sourcing, and build.",
    fullCompliance: "Full Compliance. Seamless navigation of local grid standards and ministry inspections.",
    precisionExecution: "Precision Execution. Rigorous engineering standards applied directly on site.",
    contractsManagement: "Contracts Management",
    fullLifecycleCommercialLegal: "Full-lifecycle commercial, legal, and administrative oversight to maximize returns and mitigate liability:",
    biddingAdministration: "Bidding & Administration. RFP reviews, commercial terms, and daily EPC contract management.",
    variationsClaims: "Variations & Claims. EOT requests, scope variation tracking, and claim evaluations.",
    subcontractsCloseout: "Subcontracts & Closeout. Back-to-back agreements, FIDIC risk mitigation, final accounts, and project handover.",
    operationsSupport: "Operations Support",
    advancedTechnicalTroubleshootingRootCaus: "Advanced Technical Troubleshooting & Root Cause Analysis",
    aSystematicDataDrivenApproach: "A systematic, data-driven approach to rapidly identify the root cause of complex issues in electrical, mechanical, and instrumentation systems, minimizing downtime and preventing recurrence.",
    problemDefinitionDataCollection: "Problem Definition & Data Collection",
    thoroughReviewOfSystemDocumentation: "Thorough review of system documentation, including P&ID and electrical schematic diagrams.",
    structuredAnalysisRootCauseId: "Structured Analysis & Root Cause ID",
    fmeaFaultTreeAnalysisFta: "FMEA, Fault Tree Analysis (FTA), and Cause-and-Effect (Ishikawa) diagrams to explore every potential cause.",
    solutionImplementationValidation: "Solution Implementation & Validation",
    weDevelopAndExecuteA: "We develop and execute a corrective action plan, verifying the fix restores system reliability and performance.",
    haveAScopeInMind: "Have a Scope in Mind?",
    sendUsYourRequirementsAnd: "Send us your requirements and our engineering team will get back to you with a tailored proposal.",
    requestAQuote: "Request a Quote",
    browseProducts: "Browse Products",
  },
  ar: {
    home: "الرئيسية",
    services: "خدماتنا",
    whatWeOffer: "ما نقدّمه",
    engineeringConstructionSupplyUnderOne: "هندسة وتنفيذ وتوريد تحت سقف واحد",
    deliveringSpecializedEngineeringServices: "نقدّم خدمات هندسية متخصصة إلى جانب توريد موثوق لأنظمة كهربائية وميكانيكية وأجهزة قياس — من أول رسم إلى التشغيل الكامل.",
    whatWeDo: "ماذا نقدّم",
    sixServicePillars: "ستة محاور خدمية",
    designEngineering: "التصميم والهندسة",
    designEngineeringPillarDesc: "دراسات جدوى، تصميم مفاهيمي، وهندسة تفصيلية كهربائية وميكانيكية وأجهزة قياس.",
    constructionInstallation: "التنفيذ والتركيب",
    constructionInstallationPillarDesc: "تنفيذ ميداني كامل للأنظمة الكهربائية والميكانيكية وأجهزة القياس وفق المواصفات.",
    systemCommissioningStartUp: "التشغيل التجريبي والانطلاق",
    systemCommissioningPillarDesc: "تحضير قبل التشغيل واختبارات ودعم الانطلاق لضمان تسليم سلس.",
    productSupplySourcing: "توريد المنتجات",
    productSupplyPillarDesc: "مكونات كهربائية وأجهزة قياس وميكانيكية موثوقة من كبرى الشركات العالمية.",
    operationsSupportTroubleshooting: "دعم العمليات/استكشاف الأعطال وتحليل الأسباب الجذرية (RCA)",
    operationsSupportPillarDesc: "تحليل الأسباب الجذرية واستجابة سريعة لتقليل التوقف والحفاظ على الموثوقية.",
    contractingServices: "خدمات المقاولات",
    contractingServicesPillarDesc: "مقاولات EPC شاملة، من تجهيز الموقع والتوريد وحتى التسليم النهائي، كمقاول رئيسي أو مقاول من الباطن متخصص.",
    ourEngineeringServicesInclude: "تشمل خدماتنا الهندسية",
    fiveEngineeringDisciplines: "خمسة تخصصات هندسية",
    feasibilityStudies: "دراسات الجدوى",
    technicalAndEconomicFeasibilityStudies: "دراسات جدوى فنية واقتصادية",
    conceptualDesignAndProjectScoping: "تصميم مفاهيمي وتحديد نطاق المشروع",
    siteSurveysAndDataCollection: "مسوحات ميدانية وجمع البيانات",
    electricalEngineering: "الهندسة الكهربائية",
    detailedElectricalDesignLvMv: "تصميم كهربائي تفصيلي (أنظمة منخفضة ومتوسطة وعالية الجهد)",
    powerManagementSystems: "أنظمة إدارة الطاقة",
    protectionCoordinationStudies: "دراسات تنسيق الحماية",
    loadFlowShortCircuitStability: "دراسات سريان الحمل والدائرة القصيرة والاستقرار",
    harmonicAnalysisAndPowerQuality: "تحليل التوافقيات ودراسات جودة الطاقة",
    powerSystemSimulationEtapPscad: "محاكاة أنظمة الطاقة (ETAP, PSCAD, PSS/E)",
    scadaAndAutomationIntegration: "تكامل أنظمة SCADA والأتمتة",
    mechanicalEngineering: "الهندسة الميكانيكية",
    cableTrayAndCableLadder: "تركيب مجاري وسلالم الكابلات",
    hvacSystemsDuctsDampersVrf: "أنظمة التكييف (المجاري، الدمبرات، VRF، الملحقات)",
    tankPipingPaintingInspection: "فحص الخزانات والأنابيب والطلاء",
    pipeInstallationWelding: "تركيب ولحام الأنابيب",
    nonDestructiveTestingPtRt: "الفحص غير الإتلافي — PT, RT, UT, MT",
    rotatingEquipmentInstallation: "تركيب المعدات الدوّارة",
    fireFightingSystemsPumpsSprinklers: "أنظمة الإطفاء (مضخات، رشاشات، FM200، صنابير حريق)",
    lubeOilFiltrationTreatment: "ترشيح ومعالجة زيوت التشحيم",
    structuralSteelInstallation: "تركيب الهياكل الفولاذية",
    instrumentationEngineering: "هندسة أجهزة القياس",
    fieldInstrumentSpecificationSizingPressu: "تحديد ومعايرة أجهزة القياس الميدانية (ضغط، حرارة، تدفق، مستوى)",
    controlLoopDesignAndInstrument: "تصميم حلقات التحكم وفهارس/بطاقات بيانات الأجهزة",
    hookUpDrawingsAndInstrument: "مخططات الربط وتصميم كابلات الأجهزة",
    junctionBoxMarshallingCabinetLayout: "تخطيط صناديق التوصيل وخزائن التجميع",
    fireGasFGDetection: "تصميم أنظمة كشف الحريق والغاز",
    automationControl: "الأتمتة والتحكم",
    dcsPlcScadaArchitectureDesign: "تصميم بنية أنظمة DCS / PLC / SCADA",
    controlPhilosophyAndLogicDevelopment: "تطوير فلسفة ومنطق التحكم",
    hmiDesignAndOperatorInterface: "تصميم واجهات التشغيل HMI",
    analyzerSystemIntegrationGasLiquid: "دمج أنظمة التحليل (غاز وسائل)",
    dcsPlcPanelWiringAnd: "توصيل لوحات DCS/PLC وبنية المداخل والمخارج",
    preCommissioningCalibrationCommissioning: "دعم ما قبل التشغيل والمعايرة والتشغيل التجريبي",
    fieldExecution: "التنفيذ الميداني",
    constructionCapability: "قدرات التنفيذ",
    aSingleFieldTeamExecuting: "فريق ميداني واحد ينفّذ الأعمال الكهربائية والميكانيكية وأجهزة القياس معًا.",
    contractingEyebrow: "خدمات المقاولات",
    comprehensiveEpcContracting: "مقاولات هندسة وتوريد وتنفيذ (EPC) شاملة",
    brightVolitionProvidesEndToEnd: "تقدّم الإرادة المشرقة خدمات مقاولات متكاملة للمشاريع الصناعية ومشاريع الطاقة والبنية التحتية في إقليم كوردستان وسائر العراق. وباعتبارها شركة عراقية مسجّلة مقرّها إقليم كوردستان، نجمع بين خبرتنا الهندسية المتخصصة وإدارة مشاريع قوية لتنفيذ الأعمال على نطاق كامل — من تجهيز الموقع الأولي وحتى التسليم النهائي.",
    whetherActingAsAPrime: "سواء كنّا مقاولًا رئيسيًا أو مقاولًا من الباطن متخصصًا، نضمن إنجاز مشروعك بأمان وفي الموعد المحدد ووفق التزام صارم بالأنظمة المحلية والمعايير الدولية.",
    coreCapabilities: "القدرات الأساسية",
    electroMechanicalContracting: "المقاولات الكهروميكانيكية — تركيب كامل لأنظمة الكهرباء وأجهزة القياس، وتوضيع المعدات وتكاملها لمحطات الطاقة والمنشآت الصناعية.",
    procurementLogistics: "التوريد واللوجستيات — توريد عالمي، تخليص جمركي، وتسليم مكونات هندسية عالية المواصفات.",
    projectManagementBullet: "إدارة المشاريع — إشراف كامل من مكتب إدارة المشاريع (السلامة والصحة المهنية، ضبط الجودة) والتنسيق مع سلطات الكهرباء.",
    whyBrightVolitionContracting: "لماذا الإرادة المشرقة",
    singlePointAccountability: "مسؤولية موحّدة — تصميم وتوريد وتنفيذ تحت مظلة واحدة.",
    fullCompliance: "التزام كامل — تعامل سلس مع معايير الشبكة المحلية وعمليات تفتيش الوزارات.",
    precisionExecution: "تنفيذ دقيق — معايير هندسية صارمة تُطبَّق مباشرة في الموقع.",
    contractsManagement: "إدارة العقود",
    fullLifecycleCommercialLegal: "إشراف تجاري وقانوني وإداري متكامل طوال دورة حياة المشروع لتعظيم العوائد وتقليل المخاطر:",
    biddingAdministration: "المناقصات والإدارة — مراجعة طلبات العروض، الشروط التجارية، وإدارة يومية لعقود EPC.",
    variationsClaims: "التعديلات والمطالبات — طلبات تمديد المدة، متابعة تغييرات النطاق، وتقييم المطالبات.",
    subcontractsCloseout: "العقود من الباطن والإغلاق — اتفاقيات متطابقة الشروط، تخفيف مخاطر FIDIC، الحسابات الختامية، وتسليم المشروع.",
    operationsSupport: "دعم التشغيل",
    advancedTechnicalTroubleshootingRootCaus: "استكشاف الأعطال المتقدم وتحليل الأسباب الجذرية",
    aSystematicDataDrivenApproach: "نهج منهجي قائم على البيانات لتحديد الأسباب الجذرية للمشكلات المعقّدة بسرعة في الأنظمة الكهربائية والميكانيكية وأجهزة القياس — لتقليل التوقف ومنع تكرار الأعطال.",
    problemDefinitionDataCollection: "تحديد المشكلة وجمع البيانات",
    thoroughReviewOfSystemDocumentation: "مراجعة شاملة لوثائق النظام، بما في ذلك مخططات P&ID والمخططات الكهربائية.",
    structuredAnalysisRootCauseId: "تحليل منظم وتحديد السبب الجذري",
    fmeaFaultTreeAnalysisFta: "تحليل FMEA وشجرة الأعطال FTA ومخططات إيشيكاوا لاستكشاف كل الأسباب المحتملة.",
    solutionImplementationValidation: "تنفيذ الحل والتحقق منه",
    weDevelopAndExecuteA: "نُطوّر وننفّذ خطة إجراء تصحيحي، مع التحقق من استعادة موثوقية النظام وأدائه.",
    haveAScopeInMind: "لديك نطاق عمل محدد؟",
    sendUsYourRequirementsAnd: "أرسل لنا متطلباتك وسيقوم فريقنا الهندسي بالرد عليك بعرض مخصص.",
    requestAQuote: "اطلب عرض سعر",
    browseProducts: "تصفح المنتجات",
  },
  ku: {
    home: "سەرەکی",
    services: "خزمەتگوزاریەکانمان",
    whatWeOffer: "چی پێشکەش دەکەین",
    engineeringConstructionSupplyUnderOne: "ئەندازیاری، جێبەجێکردن و دابینکردن لەژێر یەک سەقفدا",
    deliveringSpecializedEngineeringServices: "خزمەتگوزاری ئەندازیاری پسپۆڕانە پێشکەش دەکەین لەگەڵ دابینکردنی متمانەپێکراوی سیستەمی کارەبایی، میکانیکی و ئامێری پێوانە — لە یەکەم وێنە تا کارپێکردنی تەواو.",
    whatWeDo: "چیمان پێشکەشە",
    sixServicePillars: "شەش بواری خزمەتگوزاری",
    designEngineering: "دیزاین و ئەندازیاری",
    designEngineeringPillarDesc: "خوێندنەوەی گونجاوی، دیزاینی چەمکی، و ئەندازیاری وردی کارەبایی، میکانیکی و ئامێری پێوانە.",
    constructionInstallation: "جێبەجێکردن و دامەزراندن",
    constructionInstallationPillarDesc: "جێبەجێکردنی تەواوی مەیدانی بۆ سیستەمی کارەبایی، میکانیکی و ئامێری پێوانە بەپێی ڕێنماییەکان.",
    systemCommissioningStartUp: "کارپێکردنی تاقیکارییانە و دەستپێکردن",
    systemCommissioningPillarDesc: "ئامادەکاری پێش کارپێکردن، تاقیکردنەوە و پشتگیری دەستپێکردن بۆ دڵنیابوون لە ڕادەستکردنێکی ئاسان.",
    productSupplySourcing: "دابینکردنی بەرهەم",
    productSupplyPillarDesc: "پێکهاتەی کارەبایی، ئامێری پێوانە و میکانیکی متمانەپێکراو لە گەورەترین کۆمپانیا جیهانییەکان.",
    operationsSupportTroubleshooting: "پشتگیری کارپێکردن/چارەسەرکردنی کێشە و شیکردنەوەی هۆکاری بنەڕەتی (RCA)",
    operationsSupportPillarDesc: "شیکردنەوەی هۆکاری بنەڕەتی و وەڵامدانەوەیەکی خێرا بۆ کەمکردنەوەی وەستان و پاراستنی متمانەپێکراوی.",
    contractingServices: "خزمەتگوزاری پەیمانکاری",
    contractingServicesPillarDesc: "پەیمانکاریی EPC بە تەواوی، لە ئامادەکردنی مەیدان و دابینکردنەوە تا ڕادەستکردنی کۆتایی، وەک پەیمانکاری سەرەکی یان ژێرپەیمانکاری پسپۆڕ.",
    ourEngineeringServicesInclude: "خزمەتگوزاریە ئەندازیاریەکانمان لەخۆدەگرێت",
    fiveEngineeringDisciplines: "پێنج پسپۆڕیی ئەندازیاری",
    feasibilityStudies: "خوێندنەوەی گونجاوی",
    technicalAndEconomicFeasibilityStudies: "خوێندنەوەی گونجاوی تەکنیکی و ئابووری",
    conceptualDesignAndProjectScoping: "دیزاینی چەمکی و دیاریکردنی مەودای پڕۆژە",
    siteSurveysAndDataCollection: "پێداچوونەوەی مەیدانی و کۆکردنەوەی داتا",
    electricalEngineering: "ئەندازیاری کارەبایی",
    detailedElectricalDesignLvMv: "دیزاینی کارەبایی وردی (سیستەمی ڤۆڵتی نزم، ناوەند و بەرز)",
    powerManagementSystems: "سیستەمی بەڕێوەبردنی وزە",
    protectionCoordinationStudies: "خوێندنەوەی ڕێکخستنی پاراستن",
    loadFlowShortCircuitStability: "خوێندنەوەی سریانی بار، سیرکیتی کورت و جێگیری",
    harmonicAnalysisAndPowerQuality: "شیکردنەوەی هارمۆنیک و خوێندنەوەی کوالیتیی وزە",
    powerSystemSimulationEtapPscad: "شێوەیی سیستەمی وزە (ETAP, PSCAD, PSS/E)",
    scadaAndAutomationIntegration: "تەواوکردنی سیستەمی SCADA و ئۆتۆماسیۆن",
    mechanicalEngineering: "ئەندازیاری میکانیکی",
    cableTrayAndCableLadder: "دامەزراندنی کەناڵ و پێپلیکانەی کێبڵ",
    hvacSystemsDuctsDampersVrf: "سیستەمی هەواسازی (کەناڵ، دامپەر، VRF، پاشکۆکان)",
    tankPipingPaintingInspection: "پشکنینی مەخزەن، بۆری و بۆیاخ",
    pipeInstallationWelding: "دامەزراندن و پەیوەستکردنی بۆری",
    nonDestructiveTestingPtRt: "پشکنینی نا وێرانکەر — PT, RT, UT, MT",
    rotatingEquipmentInstallation: "دامەزراندنی ئامێری خولیو",
    fireFightingSystemsPumpsSprinklers: "سیستەمی کوژاندنەوەی ئاگر (پەمپ، سپرینکلەر، FM200، حەنەفیەی ئاگرکوژاندنەوە)",
    lubeOilFiltrationTreatment: "پاڵاوتن و چارەسەرکردنی زەیتی جوانکاری",
    structuralSteelInstallation: "دامەزراندنی پێکهاتەی پۆڵایی",
    instrumentationEngineering: "ئەندازیاری ئامێری پێوانە",
    fieldInstrumentSpecificationSizingPressu: "دیاریکردن و پێوانەکردنی ئامێری پێوانەی مەیدانی (فشار، پلەی گەرمی، تێپەڕبوون، ئاست)",
    controlLoopDesignAndInstrument: "دیزاینی حەڵقەی کۆنترۆڵ و ئیندێکس/کارتی زانیاریی ئامێرەکان",
    hookUpDrawingsAndInstrument: "پلانی پەیوەستکردن و دیزاینی کێبڵی ئامێرەکان",
    junctionBoxMarshallingCabinetLayout: "پلاندانانی سندوقی پەیوەستکردن و دۆلابی کۆکردنەوە",
    fireGasFGDetection: "دیزاینی سیستەمی دۆزینەوەی ئاگر و گاز",
    automationControl: "ئۆتۆماسیۆن و کۆنترۆڵ",
    dcsPlcScadaArchitectureDesign: "دیزاینی پێکهاتەی سیستەمی DCS / PLC / SCADA",
    controlPhilosophyAndLogicDevelopment: "پەرەپێدانی فەلسەفە و لۆجیکی کۆنترۆڵ",
    hmiDesignAndOperatorInterface: "دیزاینی ڕووکاری کارپێکردن HMI",
    analyzerSystemIntegrationGasLiquid: "تێکەڵکردنی سیستەمی شیکردنەوە (گاز و شلەیی)",
    dcsPlcPanelWiringAnd: "پەیوەستکردنی پانێڵی DCS/PLC و پێکهاتەی چوونەژوورەوە/دەرچوون",
    preCommissioningCalibrationCommissioning: "پشتگیری پێش کارپێکردن، پێوانەکردن و کارپێکردنی تاقیکارییانە",
    fieldExecution: "جێبەجێکردنی مەیدانی",
    constructionCapability: "توانای جێبەجێکردن",
    aSingleFieldTeamExecuting: "یەک تیمی مەیدانی کاری کارەبایی، میکانیکی و ئامێری پێوانە پێکەوە جێبەجێ دەکات.",
    contractingEyebrow: "خزمەتگوزاری پەیمانکاری",
    comprehensiveEpcContracting: "پەیمانکاریی ئەندازیاری، دابینکردن و جێبەجێکردن (EPC) بە تەواوی",
    brightVolitionProvidesEndToEnd: "برایت ڤۆلیشن خزمەتگوزاری پەیمانکاریی تەواو پێشکەش دەکات بۆ پڕۆژە پیشەسازی، وزە و ژێرخانییەکان لە هەرێمی کوردستان و سەرانسەری عێراق. وەک کۆمپانیایەکی عێراقیی تۆمارکراو لە هەرێمی کوردستان، شارەزایی ئەندازیاریی پسپۆڕمان لەگەڵ بەڕێوەبردنێکی بەهێزی پڕۆژە تێکەڵ دەکەین بۆ جێبەجێکردنی تەواوی کار — لە ئامادەکردنی سەرەتایی مەیدانەوە تا ڕادەستکردنی کۆتایی.",
    whetherActingAsAPrime: "جا وەک پەیمانکاری سەرەکی بین یان ژێرپەیمانکاریی پسپۆڕ، دڵنیامان لەوەی پڕۆژەکەت بە ئاسایشەوە، لە کاتی دیاریکراودا و بەپێی ڕێکخستنە خۆماڵییەکان و ستانداردە نێودەوڵەتییەکان تەواو دەبێت.",
    coreCapabilities: "توانا سەرەکییەکان",
    electroMechanicalContracting: "پەیمانکاریی کارەبا-میکانیکی — دامەزراندنی تەواوی کارەبا و ئامێری پێوانە، شوێندانانی ئامێر و تێکەڵکردنی بۆ وێستگەی وزە و شوێنە پیشەسازییەکان.",
    procurementLogistics: "دابینکردن و لۆجستیک — دابینکردنی جیهانی، ئازادکردنی گومرگی، و ڕادەستکردنی پێکهاتەی ئەندازیاریی ستانداردی بەرز.",
    projectManagementBullet: "بەڕێوەبردنی پڕۆژە — چاودێریی تەواوی PMO (تەندروستی و سەلامەتی، کۆنترۆڵی کوالیتی) و پەیوەندی لەگەڵ دەسەڵاتەکانی کارەبا.",
    whyBrightVolitionContracting: "بۆچی برایت ڤۆلیشن",
    singlePointAccountability: "بەرپرسیارێتیی یەکگرتوو — دیزاین، دابینکردن و بنیاتنان لەژێر یەک ڕێکخراوەدا.",
    fullCompliance: "پابەندبوونی تەواو — گەڕان بەناو ستانداردەکانی گریدی خۆماڵی و پشکنینەکانی وەزارەتەکان بە ئاسانی.",
    precisionExecution: "جێبەجێکردنی وردبین — ستانداردی توندی ئەندازیاری کە ڕاستەوخۆ لە مەیداندا جێبەجێ دەکرێت.",
    contractsManagement: "بەڕێوەبردنی گرێبەست",
    fullLifecycleCommercialLegal: "چاودێریی بازرگانی، یاسایی و ئیداریی تەواو بۆ ماوەی ژیانی پڕۆژە بۆ زیادکردنی قازانج و کەمکردنەوەی مەترسی:",
    biddingAdministration: "ئاڕاستەکردن و بەڕێوەبردن — پێداچوونەوەی داواکاری RFP، مەرجی بازرگانی، و بەڕێوەبردنی ڕۆژانەی گرێبەستی EPC.",
    variationsClaims: "گۆڕانکاری و داواکاری — داواکاری EOT، شوێنکەوتنی گۆڕانی مەودا، و هەڵسەنگاندنی داواکارییەکان.",
    subcontractsCloseout: "ژێرگرێبەست و داخستن — ڕێکەوتننامەی هاوشێوە، کەمکردنەوەی مەترسیی FIDIC، حساباتی کۆتایی، و ڕادەستکردنی پڕۆژە.",
    operationsSupport: "پشتگیری کارپێکردن",
    advancedTechnicalTroubleshootingRootCaus: "شیکردنەوەی پێشکەوتووی کێشە و شیکردنەوەی هۆکاری بنەڕەتی",
    aSystematicDataDrivenApproach: "ڕێبازێکی سیستەماتیکی بەرەو داتا بۆ دیاریکردنی خێرای هۆکاری بنەڕەتی کێشە ئاڵۆزەکان لە سیستەمی کارەبایی، میکانیکی و ئامێری پێوانەدا — بۆ کەمکردنەوەی وەستان و ڕێگریکردن لە دووبارەبوونەوەی کێشەکان.",
    problemDefinitionDataCollection: "دیاریکردنی کێشە و کۆکردنەوەی داتا",
    thoroughReviewOfSystemDocumentation: "پێداچوونەوەیەکی گشتگیر بۆ بەڵگەنامەکانی سیستەم، لەوانە پلانی P&ID و پلانی کارەبایی.",
    structuredAnalysisRootCauseId: "شیکردنەوەیەکی ڕێکخراو و دیاریکردنی هۆکاری بنەڕەتی",
    fmeaFaultTreeAnalysisFta: "شیکردنەوەی FMEA، دارەی کێشەکان FTA و پلانی ئیشیکاوا بۆ گەڕان بەدوای هەموو هۆکارە ئەگەرییەکاندا.",
    solutionImplementationValidation: "جێبەجێکردنی چارەسەر و دڵنیابوونەوە لێی",
    weDevelopAndExecuteA: "پلانی چارەسەرکردنی هەڵە پەرەپێدەدەین و جێبەجێی دەکەین، لەگەڵ دڵنیابوونەوە لە گەڕانەوەی متمانەپێکراویی و ئەدایەنی سیستەم.",
    haveAScopeInMind: "مەودای کاری دیاریکراوت هەیە؟",
    sendUsYourRequirementsAnd: "پێداویستیەکانت بۆمان بنێرە و تیمی ئەندازیاریمان بە پێشنیارێکی تایبەت وەڵامت دەداتەوە.",
    requestAQuote: "داوای نرخنامە بکە",
    browseProducts: "بەرهەمەکان ببینە",
  },
};
